### ISSUE TITLE
Fix sort buttons on "View All <facet>" overlay

### ISSUE THREAD

**Issue by johnjung** [johnjung/bmrcportal#1]
To demonstrate the issue, start from an empty search (/search/), click "View more Archives" in the sidebar, and click "View all Archives". None of the sort buttons have an effect, and relevance is not the default.

**Comment by johnjung** [comment]
This should be fixed in https://github.com/johnjung/bmrcportal/commit/4673eca7085fd65e363a1d8743a824a95f6f34c8

**Comment by MomoMoses** [comment]
8/20 confirmed - LLM
