### ISSUE TITLE
Explore more curated topics link - add another page location

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#10]
From the Index page, click on the Featured Topic highlight from the row in the middle of the page, in this case, it is "Black Nurses." The left sidebar has a link to "Explore all curated topics" underneath the image and heading of the current featured topic. This is good, but since it is falling so low on the page, this link should also appear after the link to "View search results for this topic" to increase visibility.

**Comment by johnjung** [comment]
This is now fixed in https://github.com/johnjung/bmrcportal/commit/a6e932a000de01badec95620deaebaad14f0af15, I'll push this to bmrcportal-test.lib soon.

**Comment by johnjung** [comment]
This change is now live on bmrcportal-test.lib. Please confirm that it looks ok and I'll close out this issue.

**Comment by MomoMoses** [comment]
Looks OK. We may want to consider line spacing on the front end.

**Comment by johnjung** [comment]
Ok. I'm going to close this out, but if you want to modify the line spacing too please feel free to re-open it and we'll assign it to Kathy.
