### ISSUE TITLE
NIU should be first featured collection

### ISSUE THREAD

**Issue by johnjung** [johnjung/bmrcportal#101]
In February 2022, NIU should be the first featured collection. This is now implemented on my dev machine and waiting to be pushed to test. Please note that featured collections will appear in database order- please let me know if it is important for BMRC staff to be able to adjust the order.

**Comment by MomoMoses** [comment]
Great!
Yes I can see a case where we may need to adjust the order. As long as this
isn't a big ask for now!

**Comment by johnjung** [comment]
There are two options for making the archives orderable:

First, I could include a numeric "order" field for each object, so that archives with a higher order number appear first in the sequence.

The other option is to make it so that the featured collection is updated manually, like the featured exhibit. That way you can display collections in whatever order you'd like. 

Do you have a preference between these two options?

**Comment by MomoMoses** [comment]
I like being able to set the order number. It's still "set and forget"
which is good for this content yet still adaptable.

**Comment by johnjung** [comment]
This is now implemented on my dev server and waiting to be pushed to test.

**Comment by johnjung** [comment]
This is now in place on bmrc-test. You'll see that a different archive is currently featured- this should flip over to NIU in February.
