### ISSUE TITLE
Add placeholder pages for portal integration

### ISSUE THREAD

**Issue by johnjung** [johnjung/bmrcportal#102]
jej will add placeholder pages for the PortalHomePage, CuratedTopicsIndexPage, and ExhibitsIndexPage when we integrate the portal. These will be in draft mode.

**Comment by MomoMoses** [comment]
### NOTES:
**Child pages for ExhibitsIndexPage** i.e. the ExhibitPage will have the larger set of content type options available. May need to make a placeholder to implement this. The ExhibitsIndexPage itself should be able to be created using only the types available on a Standard Page in the BMRC site. Subpages (grandchildren of ExhibitsIndex) of Exhibit page will also include the larger set of content options.

**Curated topics - featured topic** i.e. a child page of the CuratedTopicsIndexPage will also have its own structure, with some content areas limited or indicated for the admin user. May need a placeholder page for this too?

**Comment by johnjung** [comment]
(Based on our discussion yesterday I'm using the StreamField Blocks from the BMRC's StandardPage on ExhibitPages. Since ExhibitPages can include other ExhibitPages, this addresses the issue of grandchildren of the ExhibitIndexPage. Also, here are some notes about what different things in Django and Wagtail are called: "Content Types" in Django refer to different kinds of pages and other models, like Archives, that are managed by the database. Within a specific type of page, different "StreamField Blocks" can be used in Wagtail to create different HTML elements in different parts of the page. I that I understand your note otherwise, but please correct me if it doesn't seem like I do.)

We also need placeholder pages at /portal/help/ and /portal/about/. JEJ should also add a sample curated topic and a sample exhibit page.

**Comment by MomoMoses** [comment]
It appears that I am using the words "content types" to refer to what are actually "StreamField Blocks" on Wagtail pages. :)
I think these placeholders are now all in place, so I'm closing this out.
