### ISSUE TITLE
CuratedTopicIndexPage and ExhibitIndexPage use StandardPage streamfields

### ISSUE THREAD

**Issue by johnjung** [johnjung/bmrcportal#103]
This is now in place on my dev machine, waiting to be pushed to production.

**Comment by johnjung** [comment]
This is now in place on the testing server: please take a look at https://bmrc-test.lib.uchicago.edu/portal/curated/ and https://bmrc-test.lib.uchicago.edu/portal/exhibits/, and let me know how those work.

**Comment by MomoMoses** [comment]
Looks like our search bar and below links are there!

**Comment by johnjung** [comment]
Yes- but please confirm that the StreamFields on those pages work correctly. If they do, please close this issue out.

**Comment by MomoMoses** [comment]
The CT Index Streamfields seem to work fine.
Right-aligned image crams under the footnote text Streamfield though. Not sure why. Footnote works fine when placed above that section.

**Comment by MomoMoses** [comment]
The Exhibits Index Page seems fine. Tested all the Streamfields. However, I couldn't get the webfeed content item to work -- it's possible that would be a cool thing if we're highlighting something that has a related social media feed. I mean, more out in the edges, but who knows? 
I copied and pasted the webcode for the Twitter feed from the BMRC home page but to no avail.

**Comment by johnjung** [comment]
I'm not sure how the webfeed streamfield block is supposed to work...can you point me at some documentation about what it does?

**Comment by MomoMoses** [comment]
Sorry, I don't have any documentation of what Kathy did on this, or what she consulted in order to implement the webfeed streamfield.
