### ISSUE TITLE
Text on bottom of CuratedTopicPage should be editable. 

### ISSUE THREAD

**Issue by johnjung** [johnjung/bmrcportal#104]
This is now implemented on my local dev server and waiting to be pushed to test.

**Comment by johnjung** [comment]
This is now live at https://bmrc-test.lib.uchicago.edu/portal/curated/curated-topic-sample/. Please take a look and let me know if this works.

**Comment by MomoMoses** [comment]
Neither an image nor a video is able to be seen on the Curated Topic Sample page. The text is, technically, editable. But not all of the presented features in the "Bottom Text" box work. This is confusing, but could be ameliorated with hover text explanation if can't be changed.

**Comment by MomoMoses** [comment]
This works now. Not sure what was up.
The Bottom Text section now allows both video and images.
Top section(s) allow use of all the Streamfields, including the 2-3 column one. 
Sidebar is nice to have. :)

**Comment by johnjung** [comment]
This is now fixed in https://github.com/uchicago-library/bmrc/commit/f5c43282859bf37e1a0c3a125c367cd26bdd1219.
