### ISSUE TITLE
is sidebar available for Research Help page?

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#105]
This is partially implemented in https://github.com/johnjung/bmrcportal/commit/9d45e44faa84083bcbf2d5881dd85291c7b97d6a, and live on the server. I'm going to wait until phase two to evaluate whether I can add the link to the PDF document and sidebar, since we're going to be using existing page types when possible for the Wagtail integration.

_Originally posted by @johnjung in https://github.com/johnjung/bmrcportal/issues/93#issuecomment-990948300_

**Comment by johnjung** [comment]
This is now implemented on bmrc-test.lib. I do see a potential issue here: pages like https://bmrc-test.lib.uchicago.edu/portal/ have a "search member collections" searchbox at the top and portal-specific links above the footer. RIght now the help and about pages are implemented using the BMRC's StandardPage, which doesn't include those elements. I could make a PortalStandardPage that works exactly like the StandardPage, but does include these elements. 

What do you think?

**Comment by MomoMoses** [comment]
Yeah, I think we need to have our PortalStandardPage with the Portal footer elements and the searchbox etc.
If that works, it would help! 
We'd still have the sidebar available, right? if needed.
