### ISSUE TITLE
embedded video is small; can't edit size or position in the rich text block

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#108]
On the test site the video was full width -- it's OK not to always have full width, but if you use the video embed selection from a rich text block the dimensions of the embedded video screen and its position (left, centered, right) is fixed at left.
[https://bmrc-test.lib.uchicago.edu/admin/pages/124/edit/preview/](url)

Are there controls available from another type of widget? All you get on this is a box to enter the URL.
I got a link with a higher resolution from YouTube and the effect was the same.

**Comment by johnjung** [comment]
At https://github.com/wagtail/wagtail/issues/4000, I see that the Wagtail developers recommend using a StreamField to be able to configure the way videos get embedded. Please let me know if we can meet to prioritize the remaining issues: I may be able to implement this in the next week, or we can leave this for another round of work in the future.

**Comment by johnjung** [comment]
Ideally the video could either be full width or small, and if small the video should align to the right or left.

**Comment by MomoMoses** [comment]
Yes, agreed that it should be full width or small at least. It could be embedded in one of the TextColumn streamfields and fill just one column ideally.
Small video might also need to be able to be centered. 
Is Brad going to tackle this? (on his return, obviously)

**Comment by johnjung** [comment]
You'll need to talk to David Bietila for this- he'll help you spec out the work you need, and he can evaluate if and when they'll be able to take this on.
