### ISSUE TITLE
Current featured curated topic page content

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#11]
From the Index page, click on the left feature box to go to the current curated topic page; now Black Nurses.
On each of these pages (as part of the page content template) I think there should be a one-line explanation of what the heck the Curated Topics list is, near the link to go explore more topics.
Image next to the Topic scope and content note is broken. If we use a larger image on the sidebar, this can be a thumbnail size of that image.

**Comment by johnjung** [comment]
Please provide the text that should appear at the top of each curated topics page.

**Comment by MomoMoses** [comment]
Actually, I'm envisioning this explanatory text at the bottom of the page! Here is my list of content items:
1. Header = name of term 
2. Scope and content note with thumbnail image to the left
3. Link to "View search results for this link"
4. Link to "Explore all curated topics"
5. Short explanatory text about the CTL itself

Can you do some lorem ipsum for now? "The BMRC Curated Topics list was created to serve as a subject expert at your elbow! Lorum ipsum." TWO lines then. 👍

**Comment by johnjung** [comment]
This is now fixed in https://github.com/johnjung/bmrcportal/commit/ff5be2fab2d46777541e5b65174f1626b6604da9, I'll push this change to bmrcportal-test.lib soon.

**Comment by johnjung** [comment]
This change is now live on production- please confirm that it looks correct and I'll close out this issue. If there are additional issues with the curated topics template lets open additional issues for them.

**Comment by MomoMoses** [comment]
Looks correct, except for the mutant large cat. :)

**Comment by johnjung** [comment]
Ha! I'll close this out, we can re-open it if necessary.
