### ISSUE TITLE
clicking on subject heading links leads to a blank page with heading "Search" 

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#110]
<img width="521" alt="image" src="https://user-images.githubusercontent.com/3534298/150451065-8fe73b63-6d13-44e2-8ec3-62e8b682bb39.png">
this page is the basic BMRC Standard Page, also without searchbar or above the footer linked pages
clicking from a "View all relevant ... " works fine

**Comment by johnjung** [comment]
This is now fixed in https://github.com/uchicago-library/bmrc/commit/d83210753dbf74218222d66f93f4ee05903d74d8 and live on bmrc-test. I'm going to close this issue out, please reopen if necessary.
