### ISSUE TITLE
portal home page has no section / explanation for the Member Highlights

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#111]
other sections that do not allow content editing DO have a section with explanatory text.
this would be helpful for the Member Highlights too -- 1. what's contained here 2. how it cycles 3. where to go to edit the content and 4. where and how to change the cycling order.

**Comment by johnjung** [comment]
Please confirm: are you asking for additional information in the Wagtail admin for the PortalHomePage, or are you asking for an additional editable content area so that site visitors can receive this information?

**Comment by MomoMoses** [comment]
Information about how the field is populated, as you have so nicely done
with done of the others!
😊

**Comment by johnjung** [comment]
This sounds like you're requesting additional information in the Wagtail admin. This is now implemented in https://github.com/uchicago-library/bmrc/commit/f5783166edf23227b3acfc698d83f6b15b4aa6fd and live on bmrc-test.lib. Please review the text that appears in the Wagtail admin for this page. If additional changes are required, please feel free to send the exact text I should use.

**Comment by MomoMoses** [comment]
Yep this is perfect! Exactly what I was requesting.
