### ISSUE TITLE
clicking on Archives facet to filter -- logo is missing

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#113]
when facets are available on a SERP, click one of the Archives. 
result page should have the green banner at the top populated with institutional logo, name, address and link
logo is missing - check out the link text -- it's extraordinarily long!! may indicate a different issue!
[example of issue-NU](https://bmrc-test.lib.uchicago.edu/portal/search/?f=https%3A%2F%2Fbmrc.lib.uchicago.edu%2Forganizations%2FNorthwestern%2BUniversity.%2B%2528Evanston%252C%2BIll.%2529&f=https%3A%2F%2Fbmrc.lib.uchicago.edu%2Fdecades%2F1970s&sort=alpha&f=https%3A%2F%2Fbmrc.lib.uchicago.edu%2Farchives%2FNorthwestern%2BUniversity%2BArchives)

**Comment by johnjung** [comment]
This is now fixed in https://github.com/uchicago-library/bmrc/commit/6f7c4b11e369528230c409a7bbffb105d65a9df4 and live on bmrc-test.lib. I'm going to close this issue out, please re-open if necessary.
