### ISSUE TITLE
info link for NU as a repo is not the best one to use

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#114]
this got overlooked in our reviews -- the link for visiting the Northwestern U and their collections takes you directly to the Herskovitz Library of Africana studies. You'd think this would be the best page, but actually it's too limiting. there are collections in the other areas in the whole NU library system.
I think this link is better: https://www.library.northwestern.edu/libraries-collections/index.html
[better NU link](https://www.library.northwestern.edu/libraries-collections/index.html)

**Comment by johnjung** [comment]
This looks like it may involve more of a content change than just changing the target of a link in the spotlight. I'm going to assign this issue to you, please feel free to log into the bmrc.lib after we've integrated the portal into bmrc.lib and make this change using the Wagtail admin.

**Comment by MomoMoses** [comment]
???
It's just a link change.

**Comment by johnjung** [comment]
It was unclear to me whether you were talking about one of the links in the spotlight text for the PortalHomePage member highlight or the link that appears in the sidebar of the finding aid viewer. I logged into the admin panel of bmrc-test.lib and edited the Archive object for Northwestern. Please review the site to see if this fixes the issue.
