### ISSUE TITLE
exhibit sample one has a typo in the information popup

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#115]
for the image that appears on the home page.
A small version of this image will display on the portal homepage. It does NOT appera on the ExhibitPage itself.
there's a typo with the word "appear."

**Comment by johnjung** [comment]
This is now fixed in https://github.com/uchicago-library/bmrc/commit/a7bb0b1a9f8f45aa0e9d0e9d36d3b84a6e45d3ac and live on bmrc-test.lib. Please review the site to be sure the issue has been resolved. I'm going to close this issue, please re-open it if necessary.
