### ISSUE TITLE
Archive logo doesn't appear on sidebar in finding aid view

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#116]
Go to a finding aid. There is the link for access on the sidebar but no logo.
However, when the Archive is selected as a whole, it appears in the top banner as it should.

[example from Flask](https://bmrcportal.lib.uchicago.edu/view/?id=BMRC.UIC.PAYNE.xml)

**Comment by johnjung** [comment]
This is now fixed in https://github.com/uchicago-library/bmrc/commit/b85f52f58f3391637d13ae3e45e468eaf7e1bd07 and live on bmrc.lib.
