### ISSUE TITLE
featured curated topic photo doesn't appear

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#117]
I've created a child page for the Black Studies topic, with photo.
It doesn't appear in a smaller size on the sidebar of the topic page, and it doesn't appear on the home page.
[flask page](https://bmrcportal.lib.uchicago.edu/curated/black-studies)

**Comment by johnjung** [comment]
This may be happening because that curated topic is currently in draft mode. Is it possible to publish that page to see if the image will appear?

**Comment by MomoMoses** [comment]
Ha! I just now went and checked that out. Yep. That was the cause. I published, and voila! Worked.
I went back and unpublished it for now.
