### ISSUE TITLE
view and control order in which curated topics display

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#118]
Is there a way to set the order and which topic is the currently featured one? (Similar to how we control the display order of the member highlights.) 
Also possible to change or set the frequency from the admin UI, or is this by necessity a backend thing? No worries either way, just wondered what the options are.

**Comment by johnjung** [comment]
There is no way to change that order- that wasn't in the spec for this round of work. It's also not possible to change the frequency of change from the admin.

**Comment by MomoMoses** [comment]
Is is a parallel function then? That is, is the curated topics feature rotation coded similarly to the member highlight display? That is more to the point of my question. 

As you say, if the code is similar and the function works well for the member highlight, then perhaps it could be implemented for the curated topics as well.

This is definitely for a later phase enhancement.

**Comment by johnjung** [comment]
Yes, the code is similar, and each rotation function has its own function- they don't share the same function.

**Comment by MomoMoses** [comment]
great thanks. I think it wasn't too onerous a task to give control of the member highlight system, so shouldn't be too big a job for this down the line. (Fingers crossed.)
