### ISSUE TITLE
right-aligned image conflicts with footnote

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#120]
The CT Index Streamfields seem to work fine.
Right-aligned image crams under the footnote text Streamfield though. Not sure why. Footnote works fine when placed above that section.

_Originally posted by @MomoMoses in https://github.com/johnjung/bmrcportal/issues/103#issuecomment-1020472752_

**Comment by johnjung** [comment]
I don't see this in the draft of the page that is currently on bmrc.lib.uchicago.edu- if this is something you'll need for the page, could you add it to the draft so I can see the problem?

**Comment by MomoMoses** [comment]
OK, this was forwarded from a previous issue--can't replicate it, so let's leave it.
