### ISSUE TITLE
wagtail error: can't preview Help page - not happening with any other pages

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#121]
Not sure why I'm getting this error -- all other pages and previews are working just fine. Here's the error I get after saving a draft, and hitting "Preview":
"Internal server error
Sorry, there seems to be an error. Please try again soon."

**Comment by johnjung** [comment]
This is now fixed in https://github.com/uchicago-library/bmrc/commit/2a43447a52dedd3cf15b14b6a3addd1d40963a06 and live on the server.

**Comment by MomoMoses** [comment]
works now. :)
