### ISSUE TITLE
Curated Topic page: byline position

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#122]
Go to the child page "Black Studies." The byline field only allows text input; the placement and rendering is set. 

Byline appears with a lot of space above it, and is aligned left. Most bylines are closer to the text authored, also aligned right. This is a defacto standard appearance expectation.

Added benefit is that the byline won't conflict visually with the links to the search and "All" topics.

**Comment by johnjung** [comment]
This is now fixed in https://github.com/uchicago-library/bmrc/commit/645663b05b19c66d0a7d719e7392e20212eb0ae3 and live on bmrc-test.lib- you can see a sample page [here](https://bmrc-test.lib.uchicago.edu/admin/pages/122/edit/preview/). 

Please let me know if this looks ok.

**Comment by MomoMoses** [comment]
I'm confused about what changed here. The byline is still aligned left, with a fair amount of space between the text and the byline... ? Can you specify what's different?

**Comment by MomoMoses** [comment]
Looks GREAT.
