### ISSUE TITLE
Can't preview Exhibit pages (child of Exhibit Index page)

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#125]
Same error message as I got for the Research Help page:
Internal server error
Sorry, there seems to be an error. Please try again soon.

**Comment by johnjung** [comment]
Fixed in https://github.com/uchicago-library/bmrc/commit/2d8318572ea9993b7e4e72f1f4c00504b690c707 and live on the server.

**Comment by MomoMoses** [comment]
Now working, thanks!!!!!!
