### ISSUE TITLE
Repository not showing up in Descriptive Summary on finding aid

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#126]
UOC - most do not show up. 
Is populated as direct descendant of archdesc/did using the value of the repository element.
However, it may be looking for a corpname descendant rather than an address/addressline structure, which is how UOC encodes the repository name.

To view the issue, BMRC.UOC.BARRASH

**Comment by MomoMoses** [comment]
Might it be possible to test for a corpname after the repository element; if not there, then use the first addressline after the address element?

**Comment by johnjung** [comment]
This is now fixed in https://github.com/uchicago-library/bmrc/commit/2c816faaa70b42cdabed91a403142c382da33557.

**Comment by MomoMoses** [comment]
Looks good!
