### ISSUE TITLE
Metadata values for Descriptive Summary display 

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#128]
There are some values that are nesting oddly. The display may be underspecified for some of the data. 
CHM finding aid:
Letter to John Wentworth about Dr. Joseph Walker [manuscript]
DESCRIPTIVE SUMMARY
Title
Letter to John Wentworth about Dr. Joseph Walker

....
Storage Location
: Language:
  Material is in English unless otherwise noted.

The values for 852 in MARCXML are either the Repository or a physical storage location. I have no idea why the label "Storage Location" might appear, because there is no "label" attribute in this finding aid, and we don't usually display a storage location anyway. No idea why the language element is nested under this either. The language element is NOT nested in the code.

**Comment by MomoMoses** [comment]
Also, this finding aid does not show a repository.
I had thought that this value was automatic and taken from the repository abbreviation that we use to group the finding aids in the database, e.g. NU, CHM, etc. and that also appears in the eadid (filename).
That might be a better strategy, given the state of the data. If so, please make a note of it, and indicate how extensive this kind of change might be for Phase 3. (are we in phase two now?)

**Comment by MomoMoses** [comment]
In some of the new CHM finding aids converted from MARCXML, `<physfacet>` and `<dimensions>` are shown in the summary section after the extent. I'm not entirely sure that works, but also not sure where would be a better place to do that. Was this an expected result for those elements?

**Comment by MomoMoses** [comment]
Multiple creators are jammed together without spaces on one line. It's not a common practice to insert spaces or separators between these tags in the EAD code ... Is there a way to create a list, similar to how the multiple Quantity/Extent listings are created?
To view the issue: BMRC.CHM.WEISBERG-LOIS

**Comment by MomoMoses** [comment]
Ah, I think the multiple creators problem is because the parent element is `<origination>` with many children `<persname>` elements, for example. Can nested multiple elements in a list like this be displayed separated by a comma+space or something like that? 
The rule is child elements (persname, corpname) of origination are displayed in sequence with a separator.
?

**Comment by johnjung** [comment]
This is partially fixed in https://github.com/uchicago-library/bmrc/commit/6b0774f37848d7cdc5c9661f04e8003da8ad8a7e and live on the server. Please check to be sure these are working the way you expect them to.

Regarding "Storage Location"- our regularize.xsl stylesheet automatically adds a label of "Storage Location" to any `physloc` elements that do not already have one. In this case, the `physloc` element was empty, so there was nothing to display in the descriptive summary. I added some code to regularize.xsl to strip out empty `physloc` elements. 

It was straightforward to add commas between `corpname` and `persname` elements that appear inside the `repository` element- I went ahead and did that. 

Regarding physfacet and dimensions that appear in the summary section after the extent: could you provide an example that demonstrates the problem?

**Comment by MomoMoses** [comment]
The persname and corpname elements in a list are nested inside the origination element, not repository. I think you just mistyped?
Also, can we use the information in the Archives page to populate the repository info on the finding aids as well as on the finding aid sidebar and banner (when all collections for one repo are displayed)?

**Comment by MomoMoses** [comment]
as for physfacet and dimensions -- they appear without labels after extent info labelled "Size" which is not awful. lacking any better place to include that information for now, I'd say let it be, even if it looks a bit messy. Unless you have an idea? :)

**Comment by MomoMoses** [comment]
list of names in origination looks great. :)

**Comment by johnjung** [comment]
Yes, I mistyped- it's `origination`, not `repository`.

**Comment by johnjung** [comment]
Regarding the descriptive summary `repository` and `unitid`, please confirm if this is correct:

In all cases, copy the information from the appropriate Archive object to `repository/corpname` in the descriptive summary, overwriting any `repository` that is currently present. Also, always copy the `eadid` to the `unitid` in the descriptive summary, overwriting any `unitid` that is currently present.

**Comment by MomoMoses** [comment]
I would say yes to the repository question. This way we can manage the
information that gets displayed to keep it current and consistent.

For the unitid I would suggest first using any data that is there. If no
element, use the eadid. Let me sleep on this one. Or feel free to chime in.
Thanks,
Laurie

**Comment by johnjung** [comment]
Ok good. Please let me know if you'd like me to implement this when you're ready.

**Comment by MomoMoses** [comment]
Ok well I'm sleepy, but maybe that counts as sleeping on it...
let's stick with just using identifier information that's in the data for unitid, and not using a fallback of the eadid.

here's what I'm thinking: the identifier is used by the researcher interfacing with the archives staff in order to get to the collection they want to see. therefore, the only useful identifier data is one that the archives provides. the other use case is if the archives is checking which collections they've contributed.

no one is using our filename eadid values at the repositories themselves for any purpose. they are mostly for our purposes in tracking and identifying things.
done! no need to do anything! :)

**Comment by johnjung** [comment]
Ok good- so I won't do anything about the `unitid` that appears in the descriptive summary. That still leaves the repository name itself. Should I still replace the repository name in all descriptive summaries with ours, overwriting anything that's there?

**Comment by MomoMoses** [comment]
Changing the approach to OVERRIDE the data, not overwrite.
1. Use repo data from "Archives" page NOT repository element in the finding aid itself
2. can do on the fly with the regularize script (other option is upon ingest to MarkLogic)
