### ISSUE TITLE
Index page "Browse by" links on small screens

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#13]
On the Index page, when the window is re-sized smaller, the green button-style background on the words "Browse by" change to a full horizontal color bar background, with white text, on two lines.
On a larger sized window, the menu text is dark blue on a white background, and looks more clickable, and is on one line.

**Comment by johnjung** [comment]
I see what you're saying, but I'm curious about how much of a problem this will be with users. Is it possible for us to tag this as "research" and run a user test that involves browsing the site from the homepage on a mobile device?

**Comment by MomoMoses** [comment]
Ok to leave it be for now, and tag it for research. Unless Kathy has an opinion or a quick fix.
