### ISSUE TITLE
where is collection title in Descriptive Summary drawn from in the data?

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#134]
I can't tell if it's in the titleproper/titlestmt elements in the eadheader/filedesc section OR if it's taken from the unittitle element in the archdesc section.
`      <filedesc>
         <titlestmt>
            <titleproper>American Friends Service Committee records, <date
                  normal="1931/1967" type="inclusive" era="ce" calendar="gregorian">1931-1967</date>
            </titleproper>
         </titlestmt>`
If this section, it would seem that the nested date should appear after the space in the title. It does not, but the comma does appear.
If from this section, there shouldn't be a comma.  `<unittitle label="Title">American Friends Service Committee records <num type="EAD FA"
               >MSAFSC67</num></unittitle>`

**Comment by MomoMoses** [comment]
It appears that the top title in green is taken from the titleproper element whereas the Descriptive Summary title is taken from the unittitle element.
Is this the case? If so, what was the rationale, and is that what we want, or should it be uniform in some way?

**Comment by MomoMoses** [comment]
The top title (titleproper element) may not be pulling in the date because it is encoded simply as `<date>` not as a `<unitdate>` --would this cause the issue?

Can we pull in this date for titles with embedded dates? It's fairly common to do this, but naturally it's done in a variety of ways.

**Comment by MomoMoses** [comment]
Is there a need to specify the MSS number again in the `<unittitle>` element when there is a `<num>` element embedded? Maybe we could skip that `<num>` element without any harm?

**Comment by MomoMoses** [comment]
Logically, it makes sense to use the "published" title in the titlestmt/titleproper section, which is about the finding aid document itself, for the SERP list titles and the top title in the finding aid display. And then to use the unittitle data for the field "Title" in the Descriptive Summary.

HOWEVER, it is also fine to use ONLY ONE of these data sources for BOTH, if the data supports this approach.

**Comment by MomoMoses** [comment]
Another alternative here to expedite this whole thing is to manually edit the UIC finding aids as needed. There are about 50 new ones. 🥇

**Comment by MomoMoses** [comment]
Manual editing is the less optimal approach.
1. can we gather in the `<date>` elements if we continue to use the `<titleproper>` element for the SERP?
2. similarly, if we continue to use the `<unittitle>` for the Title in the Descriptive Summary, can we _exclude_ any `<num>` elements that are nested within it?

**Comment by johnjung** [comment]
We should be able to improve how the system uses titles in different places. 

There are two places titles get pulled from- there is always exactly one `<titleproper>` at:
ead:eadheader[1]/ead:filedesc[1]/ead:titlestmt[1]/ead:titleproper[not(@type="filing")]

And there is always exactly one `<unittitle>` at:
ead:archdesc[1]/ead:did[1]/ead:unittitle[not(@type="filing")]

I think we should standardize on using titleproper for SERP snippet titles and the `<h1>` on the finding aid view, and we should use unittitle for the title in the descriptive summary. 

In all cases, any `<num>` elements should be suppressed, and all other elements should be rendered. 

Here is some reporting to help with testing:

Descendants for `<titleproper>`-
263 `<date>` elements, see BMRC.HARSH.WYATT.xml.
3 `<emph>` elements, see BMRC.DEFENDER.INDIVIDUALS.xml.
918  `<num>` see BMRC.EHC.CR_HRC.xml.

Descendants for `<unittitle>`-
3 `<emph>`, see BMRC.DEFENDER.INDIVIDUALS.xml. 
42 `<num>`, see BMRC.UIC.WINSLOW.xml. 
42 `<unitdate>`, see BMRC.NU.FERRIS.xml.

Does this sound ok?

**Comment by MomoMoses** [comment]
I like this approach!

**Comment by johnjung** [comment]
This is now fixed in https://github.com/uchicago-library/bmrc/commit/846d1a7d074eeda2f723eefcf34f13b44a36206f, and live on bmrc-test.lib. The titles that appear in the SERP and in the h1 of the finding aid view should match now- num elements inside titles shouldn't display, but other elements should. 

There are a lot of edge cases for this one, so please take a look at bmrc-test and let me know if it's ok or if there is more I can do.

**Comment by MomoMoses** [comment]
Is there a way not to have "Guide to the" before the collection title? I think you're seeing that in the titleproper element. The alpha listing is already problematic without adding this wrinkle. (It now alphabetizes using "the", "a", etc.

**Comment by johnjung** [comment]
I'd like to evaluate this in the context of https://github.com/johnjung/bmrcportal/issues/139, but after we push the current round of changes to production.

**Comment by MomoMoses** [comment]
Is this a good time to evaluate the whole TITLE mess? LOL

**Comment by MomoMoses** [comment]
1. Jej to send report on all the titles that appear in eadheader/filedesc/titlestmt/**titleproper** for LL to check for other issues that may surface when we switch to using this element for search and browse + the H1 in the finding aid view.
2. The title that appears in the DESCRIPTIVE SUMMARY in the Finding Aid view will be taken from archdesc/did/unittitle, which is at the collection level. (I believe this is how we are already handling it.)
3. Once the switch to the titleproper in the eadheader is approved, this change should be implemented.

**Comment by MomoMoses** [comment]
NOTE: since our ingest process only checks for well-formed XML, any non-compliant EAD that is well-formed will still pass. In the case of titles, if the titleproper element is not in the finding aid even though it is a required element, the finding aid will be ingested, but the Search, Browse, and H1 will all read "Untitled" and the finding aid will be sorted under the letter "U." This will act as a flag to the error, to be communicated to the institution so that they may fix the issue internally and re-submit for the BMRC Archives Portal.

**Comment by MomoMoses** [comment]
Would there be an issue with simply using `<unittitle>` from the archdesc/did/ chunk of code? I'm not sure why we went with other sources for the SERP snippets and H1 on the finding aid view. Can you illuminate?

We could compare a report listing the data in unittitle and another listing of the data in the eadheader/filedesc/titlestmt/titleproper and see what differences there are. That should inform the decisions on this I think. If it works, I feel that simpler is always better. :)

**Comment by MomoMoses** [comment]
Decision 8/30/2022: In XQuery, the title data for SERP and H1 finding aid view will be pulled from the eadheader child element. Approval received from UChicago, which had the section marked "internal." (Elements marked "internal" will not be processed by the XSLT script.)
See above suggestion for report and simply using the unittitle element (child of archdesc) for EVERYTHING.

**Comment by MomoMoses** [comment]
Looks to me like the <archdesc_did_unittitle> source results in the cleanest data. I would say, let's use this one only for all places where the title is displayed.

Only caveat to that is that for some titles from <archdesc> there are commas after the data in the field to accommodate display of the next field in combination with the title. We should create a regex rule to exclude commas at the end of the <unittitle> data.

**Comment by MomoMoses** [comment]
Notes: 8/15/2022 meeting: `<eadheader>...<titleproper>` is required, whereas `<frontmatter>` is optional. In fact `<frontmatter>` is deprecated and not used in EAD3.
Note that the ingest script checks for XML well-formedness but NOT for EAD compliance. "Untitled" will display if non-compliant, in SERP and as the H1 finding aid view.

**Comment by MomoMoses** [comment]
sorry - didn't mean to close this prematurely!

**Comment by johnjung** [comment]
That's not a problem. Please confirm if this is correct:

Titles appear in multiple places in the interface:

1. At the top of each search snippet on a search result page (e.g., https://bmrc.lib.uchicago.edu/portal/search/?q=chicago)
2. In the `<h1>` element of an individual finding aid view (e.g., https://bmrc.lib.uchicago.edu/portal/view/?id=BMRC.CHM.ACHEN.xml)
3. Next to the "title" label under "DESCRIPTIVE SUMMARY" on an individual finding aid view.

We will be updating titles 1 and 2, but not 3. Titles 1 and 2 should pull from archdesc/did/unittitle. Titles should include all descendant text nodes. Whitespace should be normalized (e.g., multiple spaces, tabs or newlines should be converted to a single space) and trailing commas should be removed. If an archdesc/did/unittitle is empty or not present, return the title "Untitled".

**Comment by MomoMoses** [comment]
This sounds right. Just to note that 3 already draws from the proposed new data source for 1 and 2.

I’m not sure about all the descendant text nodes. Should we run a report first?

**Comment by johnjung** [comment]
Thanks very much, Laurie. Just to clarify, how does 3 draw from the new data source for 1 and 2? Also, the report I just generated includes all descendant text nodes- so that's what you've been looking at, I just wanted to document that specifically.

**Comment by MomoMoses** [comment]
That's what it always has done

**Comment by johnjung** [comment]
This is now fixed in https://github.com/uchicago-library/bmrc/commit/27918b46b9040e0c3c7aecdad55544fd4f66b0cb, and live on bmrc.lib. Please take a look- if everything looks good we can close this issue out.

**Comment by MomoMoses** [comment]
The titles all look so much cleaner this way! Thanks. Finding other errors, but this looks complete!
