### ISSUE TITLE
Wagtail: page names, slugs and URLs

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#138]
The page name appears as a heading at the top of the page. this is at times problematic, such as on the home page.
IF the page name is "BMRC Archives Portal" instead of "Portal" though, the breadcrumbs, and URL changes doesn't it?
Or, if the slug is edited, does that allow for using a different page name, while still maintaining a simple URL like "/portal"?

**Comment by johnjung** [comment]
When you first create a page, Wagtail automatically creates a URL slug that matches the page title- however, if you click the "Promote" tab while editing a page in the Wagtail admin, you can set your own slug. For example, right now, the portal home page has "BMRC ARCHIVES PORTAL" as the title, and "portal" as the slug.

Does this do what you want it to, or is there still a problem?
