### ISSUE TITLE
"View all" modal: selected terms 

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#14]
To demonstrate the issue, start with an empty search. Then select topic headings from the sidebar to limit number of results. Example, choose these 2 terms:
Chicago (Ill.)--Race relations (8) 
African Americans--Civil rights (8)
Then choose "View more topics" and again choose "View all related topics". More topics appear, but the list does not include all of the topics already listed in the sidebar. For the modal to be complete with the understood meaning that this list is ALL the relevant topics, it would have to include everything from the sidebar as well as new topics in addition to those that didn't fit in the sidebar list.

**Comment by johnjung** [comment]
I see this is currently implemented in two different ways in the site. Using your example above, in the sidebar, selected facets are presented as text, while selectable facets are presented as links that can be clicked. Currently in the "view all" popup, selected facets do not appear. 

We talked through the sidebar behavior when we were designing the site, so it seems to me that the best solution is to add selected facets to the "view all" popup as text. 

Please confirm- does this make sense to you?

**Comment by MomoMoses** [comment]
OK, yes, this would indicate that the selected terms are still in operation, and when you select a term from the "view all related" it operates exactly as the other selected terms worked when selected from the smaller list.
Only caveat would be if the visual is unsatisfactory, which we can leave to Kathy to help us.

**Comment by johnjung** [comment]
This is now updated in https://github.com/johnjung/bmrcportal/commit/c64d1dbbe800227cb8449ba7f031d1832cc643f8, and live on bmrcportal-test. Please take a look and let me know if this works.

**Comment by MomoMoses** [comment]
I had thought the selected terms would look as they did on the main page (highlighted, with an "x"), but this seems understandable to me. Let's ask Kathy if the already selected, non-clickable terms should look more different.

**Comment by johnjung** [comment]
Do we have a mockup for the modal window?

**Comment by MomoMoses** [comment]
here is the mockup for the modal window -- it's from the SERP where "View all [relevant] Archives" has been selected.
[Example mockup for modal](https://uchicago.box.com/s/ftxx34pvqt9d6o3q7hsx9802c8m4b8ab)

**Comment by johnjung** [comment]
Based on the update we just did for https://github.com/johnjung/bmrcportal/issues/20, what do you think about this as a solution?

Style active terms in the modal popup as dark gray, italic text, to match the way active terms are style in the search and browse sidebars. 

I'm concerned that if we add a green background to those terms, then their affordance as clickable objects on the page will go way up, even though they're not actually clickable. However, if we style them as italic text, we'll be using the same styling to signify active terms as we do elsewhere in the interface. 

What do you think? 

(While I'm at it I can remove the bullets from the popup, so the site will match the mockup more closely.)

**Comment by MomoMoses** [comment]
Looks good - the term was not in italic on the modal window.
I'm of two minds about the italic in the sidebar having seen this -- the regular text in black looks kinda good. But it should be consistent in any case.

**Comment by johnjung** [comment]
Return to this after https://github.com/johnjung/bmrcportal/issues/42.

**Comment by johnjung** [comment]
This is now implemented in https://github.com/johnjung/bmrcportal/commit/6151260f84915acc4901e3006bb9dbbdb13e6f49 and live on the server. I'm closing this issue out, please re-open if necessary.
