### ISSUE TITLE
Label anomaly for "Dates" - appearing in large green letters, similar to the issue with "Quantity" 

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#140]
Appears in NU finding aids so far, e.g. BMRC.NU.CITIZENS_FOR65.xml
Similar to what we found with the label "Quantity" appearing alongside "Size" in the Descriptive Summary section of the finding aid display. The `<unitdate>` element has a label attribute in this case.

Also occurs with BMRC.NU.UNIV_THEATRE_PHOTO.xml finding aid display. Could possible be a NU idiosyncrasy.

**Comment by johnjung** [comment]
This is now fixed in https://github.com/uchicago-library/bmrc/commit/21cdb72bf363ddf045056ce5d02062a717299892 and live on the server.

**Comment by MomoMoses** [comment]
Excellent.
