### ISSUE TITLE
Type of container given only in a "type" attribute, does not display data

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#142]
The example is BMRC.NU.UNIV_THEATRE_PHOTO.xml
Physical Description: 22.00  without any idea of container name or measurement is not great. 22 of what? It's given in the "type" attribute of the <extent> element. It should be possible to use that to add to the text node.

(It's only 50 examples, however, so if time runs out, it's possible to manually edit, though it's always best to have an automatic solution if possible for posterity.)

**Comment by johnjung** [comment]
This is now fixed in https://github.com/uchicago-library/bmrc/commit/6e4514baa6f61e4ea88f481b1c9fcad1a697ba10 and live on the server.

**Comment by MomoMoses** [comment]
this looks great on the finding aid!
the SERP still has a blank. maybe this is part of the other issue.

**Comment by MomoMoses** [comment]
Even with the fix on the other Extent issue, there are still data values that say "Size: 22" without a qualifier on that amount. These appear to be where the label is hidden in the attribute "type" and does not appear as a text node anywhere else.
Example: BMRC.NIU.BLK_STUDIES_CTR.xml

**Comment by johnjung** [comment]
Note to self, see https://github.com/johnjung/bmrcportal/issues/141 for some reporting on physdesc and extent elements.

**Comment by johnjung** [comment]
Ok, I have a fix in place in https://github.com/uchicago-library/bmrc/commit/b85de969544868827ad40ea9a4c84dc97f543056. This is live on bmrc-test.lib- please let me know if it looks ok there there, and if it does I'll push the change to production.

While I was fixing this I improved handling for situations where there are multiple physdesc and extent elements in a single finding aid- for two examples see BMRC.DEPAUL.DPU-STUDENT-AFFAIRS.xml (search "depaul student affairs") and BMRC.IIT.PROGR-COMMUNITY-CHURCH.xml (search "progressive community church").

**Comment by MomoMoses** [comment]
these look great! glad this issue presented an opportunity for improved handling!!! :)
