### ISSUE TITLE
Decades facet seems to be including 3-digit numbers

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#143]
To view the issue, take a look at [Daley collection](https://bmrc.lib.uchicago.edu/portal/view/?id=BMRC.UIC.DALEY-RICHARD-J.xml) and search for "338". This collection is included in a Decades facet for the "3380s".

Another collection in the 3380s facet is the [Illinois Central RR Company](https://bmrc.lib.uchicago.edu/portal/view/?id=BMRC.NEWBERRY.ILL-CENTRAL-RR.xml)

In neither collection is there a "year" with the 4-digit number 3380.
These two collections also have materials from the decade 2860s. Amazing!

**Comment by MomoMoses** [comment]
Newberry collection [Waller-Beckwith](https://bmrc.lib.uchicago.edu/portal/view/?id=BMRC.NEWBERRY.WALLER-BECKWITH.xml) has a bunch of weird years, but I only found one error. The others seem to be picked up from folder numbers, which is strange.

**Comment by johnjung** [comment]
Hi Laurie,

These "amazing" dates are because of dirty data-

BMRC.UIC.DALEY-RICHARD-J.xml 
contains the following XML:

`<unitdate type="inclusive" era="ce" calendar="gregorian">33830</unitdate>`

"33830" is nonsense here, but because the browse finds four digits in a row it places this in the 3380s. 

BMRC.NEWBERRY.ILL-CENTRAL-RR.xml
contains the following XML:

`<unitdate>Jun. 10, 1891-May 1, 1902; nos. 5990-6338; 6352 [scattered]</unitdate>`
`<unitdate>Jan. 4, 1898-Nov. 1, 1894; nos. 2782-5989</unitdate>`

The decade browse is set to consider four-digit numbers separated by dashes as sequences of years. Here, the strings "5990-6338" and "2782-5989" should probably not be encoded inside the `<unitdate>` element. Having those strings there creates a large number of futuristic looking decades in the decade browse.

**Comment by MomoMoses** [comment]
Yes, futuristic! Darn it, I wish we actually had those dates for real. That would be in the Sun Ra collection. :)

I knew it was bad data, but I couldn't find it! Your methods are superior, no surprise there. 

I'll do my best to remove the most egregious examples. The Newberry encoding is, indeed, erroneous. I did correct a few stray zeroes when a nine was desired--easy typing mistake to make.

**Comment by MomoMoses** [comment]
reopening this purely as a note to self to take out the worst offenders in the data!

**Comment by MomoMoses** [comment]
Would you be able to check this file for erroroneous dates? None of my search methods seem to be effective or efficient... :(
BMRC.NEWBERRY.CHICAGO-READER_PHOTOS.xml
and 
BMRC. NEWBERRY.CHICAGO-READER_NEWS-PHOTOS.xml
They are causing a result in almost all the weird decades.

BMRC.UIC.AFSC.xml

**Comment by johnjung** [comment]
I see the following `<unitdate>` elements in those documents:

BMRC.NEWBERRY.CHICAGO-READER_PHOTOS.xml:
```
 <unitdate label="Dates">1008-1998</unitdate>
 <unitdate label="Dates">2994</unitdate>
 <unitdate label="Dates">1992</unitdate>
```

BMRC.NEWBERRY.CHICAGO-READER_NEWS-PHOTOS.xml:
```
<unitdate label="Dates">1307</unitdate>
<unitdate label="Dates">1637</unitdate>
<unitdate label="Dates">1871-1988</unitdate>
<unitdate label="Dates">2648</unitdate>
<unitdate label="Dates">2871</unitdate>
<unitdate label="Dates">3009</unitdate>
<unitdate label="Dates">3259</unitdate>
```

Here's how I'm doing the search. In cases where I see a single decade that looks weird in the browse, I search for `unitdate.*yyy` where yyy is the first three digits of the year- e.g., `unitdate.*300` to find something from the 3000s. 

Then, in cases where I see a sequence of decades that look weird, like 2780s, 2790s, etc. I look for the first three digits of the first decade, followed by a slash: `unitdate.*278.*-`. 

(In the above search strings, ".*" means "zero or more of any character.")

**Comment by MomoMoses** [comment]
Just a note that this appears to be enhanced EAD after ingest? I don't find these labels in the original encoded document.

**Comment by johnjung** [comment]
Yes, those labels are added in the regularization step- it's happening just before ingest, but it's true that they're not in the original documents.

**Comment by MomoMoses** [comment]
I fixed everything I could find so far. Will check again after reload.

**Comment by MomoMoses** [comment]
UIC's American Friends Service Committee shows up in the Decades for 1700s. No earthly idea why--I cannot find any errors.
[AFSC finding aid page](https://bmrc.lib.uchicago.edu/portal/view/?id=BMRC.UIC.AFSC.xml)

**Comment by johnjung** [comment]
I see that finding aid has been edited recently- one of the `<unitdate>` elements was changed from 1656 to 1956. That will remove this finding aid from a lot of superfluous decade browses, include 1700s.  I see that on #166 we're scheduled to reload the finding aids on Friday morning- the reload should take care of this issue too.

**Comment by MomoMoses** [comment]
thanks for all the detailed queries, etc. I believe this is complete -- for now! 8/5/2022 that is.
