### ISSUE TITLE
Fix order of Browse by facets on Index Page to match sidebar order

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#15]
Note the order of facets on the Index page in the Browse by menu:
Topics | People | Places | Organizations | Decades | Archives
The order of facets from a Browse page to view all items in a facet is in the above order as well.

Note the order of facets on the LH Sidebar on SERP - this is the preferred order.
Topics | People | Organizations | Places | Decades | Archives

**Comment by johnjung** [comment]
If this is part of the spec, could we move this issue from here into https://github.com/momoMoses/portal-specs/, or somewhere similar? I'd like to use this space for bug tracking only, if possible. 

(Alternatively, if this is a bug please just let me know what to change.)

**Comment by johnjung** [comment]
Ok, this is fixed in https://github.com/johnjung/bmrcportal/commit/3906113cf5fb9c107399253f3f039d406a8f898f. I'll push this change to bmrcportal-test.lib soon.

**Comment by johnjung** [comment]
This is now live on bmrcportal-test. I'm going to close this issue out, but please reopen if necessary.
