### ISSUE TITLE
how is data parsed in <unitdate> element with text mixed with numbers?

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#151]
For example, if there is a value in a `<unitdate>` element that include "ca. 1949" would that collection appear in the 1940s decade? It seems to me that it should. Also "ca. 1950s". The trailing "s" may make it moot. Ditto for "ca. 1940s-1950s." Finally, how would this one appear: "1939-ca. 1950"?

What about this example: "undated-1937"? Would it appear in 1930s or would it be skipped because of the word "undated" appearing within that element?

Similarly, "November 2001" -- in the 2000s?

**Comment by johnjung** [comment]
[Here's the function that deals with this](https://github.com/uchicago-library/bmrc/blob/87ad702295791d467fe493aa200e8cadfb26fd70/portal/__init__.py#L167). 

First, the function creates a list of years by looking for four digit years and dashes. If it finds a four digit year on its own it adds it on its own, but if it finds two four digit years separated by dashes it adds all of the intervening years too. It ignores text like "undated" or "ca.". 

Once it has a list of years, it converts those years into decades by chopping off the last digit of the year and replacing it with "0s" - so "1940" and 1949" both return the "1940s" decade. 

Here are some examples:

"ca. 1949" -> "1949" -> "1940s"
"ca. 1950s" -> "1950" -> "1950s"
"ca. 1940s-1950s" -> "1940" , "1941", "1942", ... "1950" -> "1940s", "1950s"
"1939-ca. 1950" -> "1939", "1940", "1941", ... "1950" -> "1930s", "1940s", "1950s"
"undated-1937" -> "1937" -> "1930s"
"November 2001" -> "2001" -> "2000s"

**Comment by MomoMoses** [comment]
Cool! I presume that a full date like 10/31/2001 would also parse?

**Comment by johnjung** [comment]
Yes, it will- in the example above, the code will find the four digits "2001" and parse those as a year.

**Comment by MomoMoses** [comment]
Ah, but what if it has instead "3/31/01"?

**Comment by johnjung** [comment]
The system requires four-digit years. In the case above the code would need to know something about the context around the date to tell if that refers to the year 2001, 1901, or something else. Using the format above we would need a lot of code to be able to parse dates like 11/10/12. That code sounds fun to write, but I wonder if it's the best use of dev time. 

To me it seems reasonable to expect that best practices would encourage finding aid authors to encode four digit years with four digits. Is that the case, or not?

**Comment by MomoMoses** [comment]
Oh, you are so optimistic and positively positive-thinking!
Well, sure, 4-digit years in dates is far preferable. So is, to my mind, spelling out "undated" vs. "n.d." yet many many documents have the latter.
Definitely NOT the best use of dev time! LOL. If it's egregious at some point, I could clean up the data using open refine or something maybe. :)
PS I could also alert staff at member institutions about these preferences/things that make their EAD more data-versant.
