### ISSUE TITLE
Curated topics link broken in the site footer

### ISSUE THREAD

**Issue by johnjung** [johnjung/bmrcportal#153]
The portal-specific footer on [https://bmrc.lib.uchicago.edu/portal/](https://bmrc.lib.uchicago.edu/portal/) contains a link to "Curated Topics"- that link points to [https://bmrc.lib.uchicago.edu/portal/curated/](https://bmrc.lib.uchicago.edu/portal/curated/). However, the curated topics index page currently lives at [https://bmrc.lib.uchicago.edu/portal/curated-topics-index/](https://bmrc.lib.uchicago.edu/portal/curated-topics-index/).

Originally, I planned that the site would use the shorter URL, and to save development and page rendering time, I hard-coded the link to /curated/ into the footer. 

I think there are three ways to solve this problem:

- An editor could change the slug of the curated topics index page to "curated" in the Wagtail admin. 
- A developer could change the hard-coded link to the curated topics index page in the template, so that the link points to "curated-topics-index".
- A developer could make the footer link dynamic, so that whatever slug you're currently using will work. 

Do you have a preference for one of these solutions over the others?

**Comment by MomoMoses** [comment]
It seems more flexible to have the link be dynamic, but is that a quick change? Could be better uses of your time. It's a simple matter to change it back to "curated".

**Comment by johnjung** [comment]
I think the better solution is to change the slug to "curated" and leave it there- that lets me focus more time on bug fixing.

**Comment by MomoMoses** [comment]
Done!
