### ISSUE TITLE
stray fields/green words in the Descriptive Summary

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#154]
Edge case for sure: this one is for the rare few who have a variant title -- there can't be that many. If need be, I can just clean up the EAD. 
here's an example: BMRC.UIC.CITY2000.xml at [UIC City2000 finding aid](https://bmrc-test.lib.uchicago.edu/portal/view/?id=BMRC.UIC.CITY2000.xml)

**Comment by johnjung** [comment]
If there is a clear way to edit the finding aid to display correctly, and there aren't too many of these, then it may be easiest just to edit the finding aid in this case. If you'd like me to review the code, what are the stray fields/green words?

**Comment by MomoMoses** [comment]
Hmm. They vary. We have seen Dates and quantity, but I think you fixed
that. I'll have to revisit this one.

**Comment by johnjung** [comment]
Ok- please let me know if you find anything that needs to be fixed on my end.

**Comment by MomoMoses** [comment]
Let's close this issue and re-open if issues appear after most recent re-load.
