### ISSUE TITLE
Effect of "audience=internal" on title

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#155]
UChicago makes this internal:
```
<filedesc>
   <titlestmt>
    <titleproper>
```

and this is marked for an external audience:
```
<frontmatter audience="external">
  <titlepage>
   <publisher>University of Chicago Library</publisher>
   <titleproper>
```

Both are `<titleproper>` elements, but I think it is the former that our code draws upon, is that correct? Not sure if any other repository marks the former "internal" or not, but if this is our data source, it would not display in that case. My strategy is to delete the attribute, but this is not optimum.

**Comment by johnjung** [comment]
Is there an issue that a specific finding aid demonstrates here? Also, when you say that our code draws on one title or the other, could you let me know where in the interface you're expecting to see that title? (Because titles appear in different places in the EAD, knowing which title you're thinking about will help.)

**Comment by MomoMoses** [comment]
That would be in the header before the archdesc element.

**Comment by johnjung** [comment]
Ok- for the h1 on the finding aid view, and for titles on search and browse pages, we use the latter title. Here's the complete XPath:
/ead:ead[1]/ead:frontmatter[1]/ead:titlepage[1]/ead:titleproper[1]

Please let me know if I can help with anything else on this one.

**Comment by MomoMoses** [comment]
QUESTION: if the titleproper element in the eadheader is marked "internal" as it is in UChicago's finding aids, will it not display even though we are attempting to use that element for Search/Browse/H1?
What will alert us to the issue in the display? Blank title areas? 
To resolve this issue can we make an exception to the "do not display" handling of anything marked "internal"? (Not sure why UChicago makes the eadheader "internal," but surely they didn't necessarily intend the title of the collection to be hidden! :)

**Comment by MomoMoses** [comment]
See issue #134

**Comment by MomoMoses** [comment]
UChicago Special Collections and Archives gave the go-ahead to take the data from this elements, even though it is marked "internal." This practice started before the current staff's tenure. 
TBD on review after this change to see if other data issues are created from this change. Closing now, can re-open if necessary.
