### ISSUE TITLE
Accessibility: clickable logo in header

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#157]
Logo in the header block is being highlighted as not having alt text.
Need to specify "BMRC logo shows archival file box, with folders inside"

**Comment by johnjung** [comment]
This is now fixed in https://github.com/uchicago-library/bmrc/commit/427da61b4bdd0e0a44f1b1663f749f8cc4167f5b, and live on both bmrc-test.lib and bmrc.lib. I'm going to close this issue out, please feel free to re-open if necessary.
