### ISSUE TITLE
Error message for no site search results points to old link

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#160]
Enter "sesame street" in the search website box and hit return.
No results, but it suggests, "would you like to search our collections?" 
first, the question should not say "our" but rather "member" collections.
second, the link goes to the old search page -- needs to be updated to the new BMRC Archives Portal page.

**Comment by johnjung** [comment]
This is now implemented in https://github.com/uchicago-library/bmrc/commit/0bdfb6c5ab0fe41b43b3ea36812926a80c639126 and live on bmrc.lib. Please take a look- does this work ok?

**Comment by MomoMoses** [comment]
Uh. I'm getting two results now for a "sesame street" search. And they're correct!!! Have to find a new use case.

finally found one: "johann bach"! The error messages are great.
