### ISSUE TITLE
Accessibility: two links in same context, different targets

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#163]
but it's from 2017! I can't even get to it! 
which is why I discourage link texts like "click here". :(
[2017 news article that offends](https://bmrc.lib.uchicago.edu/news/bmrc-featured-university-chicago-library-newsletter/)

**Comment by johnjung** [comment]
This shows up in Siteimprove as "Links in the same context with the same text alternative". The article originally included two links with the link text "here":

"For the whole newsletter, click here. To go directly to the BMRC article, click here."

I moved the link to Libra itself to the first place in the entire text where Libra is mentioned ("Libra is a newsletter for faculty and the University of Chicago community...") and I changed the last sentence to "Go directly to the BMRC article."

Please take a look at this page and at the Siteimprove report to confirm that this takes care of the issue, and if so, please feel free to close this out.
