### ISSUE TITLE
Curated topics

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#19]
To demonstrate the issue, choose a facet from the Browse bar menu. From this page, viewing, for example, All Organizations [https://bmrcportal-test.lib.uchicago.edu/browse/?b=organizations#](url) , click on the link for the Featured Topic from the Sidebar, in this case "Black Nurses." 
Nothing happens. There is now a dummy of the Featured Topic page so it should go to that page. This content should populate dynamically from the Topic of the week content that is stored (where?) and is tagged for a given week (?). [I'm not sure how this page is populated, or whether we in fact create 52 pages! To be displayed on their respective dates.]

**Comment by MomoMoses** [comment]
[Example of Featured Curated Topic page content.docx](https://github.com/johnjung/bmrcportal/files/7390983/Example.of.Featured.Curated.Topic.page.content.docx)

**Comment by MomoMoses** [comment]
See issue #84

**Comment by MomoMoses** [comment]
For now, this page can be like the "About the Portal" page which links to a "coming soon" page. It will be good to have something that happens when people click on links to view all curated topics. from anywhere on the site.
That is: 1. at the bottom of the Featured Topic page, 2. in the Footer, 3. below the feature block for the topics on the home page.

**Comment by MomoMoses** [comment]
Here is the narrative to go on the **BMRC Curated Topics** page:
### BMRC Curated Topics List
The BMRC’s Curated Topics List is a work-in-progress designed to help remedy the pervasive invisibility of primary source material documenting Black history and culture. We’re inviting people who work with collections on Black experiences to tell us what topics are most important in their work, that may resonate deeply with users. It will comprise a special vocabulary that concisely encapsulates the subject domain as a dynamic body of knowledge--like having a subject matter expert at your elbow! 

The project is in development now–if you are a scholar, educator, reference librarian, enthusiast, or researcher in Black Studies, get in touch! We need you to help create a robust and relevant resource for studying Black history and culture. Want to know more, or join the project team? Email the Project Archivist, Laurie Lee Moses at lmoses@uchicago.edu

**Comment by MomoMoses** [comment]
Marcia is planning to write up a topic (so it would link to a page exactly like the "Black Studies" page.
Plus she had agreed to provide several more topics of interest as candidate topics for the page to demonstrate what the project is all about. They will simply be listed, not linked to anything.

**Comment by MomoMoses** [comment]
Please see the new 12/8 document on Box for the Curated Topics text. Word doc that included home page content from a different issue is superseded by this document for the Curated Topics portion.

**Comment by johnjung** [comment]
Please confirm exactly what changes I still need to make for this issue.

**Comment by MomoMoses** [comment]
OK, coming right up!

**Comment by MomoMoses** [comment]
Box doc with [final copy](https://uchicago.box.com/s/jj8qfjjrhfh3xcezr8de8jhry1me3o9x)

**Comment by johnjung** [comment]
This document seems to contain two different versions of the content for the "view all curated topics" page, and one paragraph to be included at the bottom of the featured curated topic. 

Tomorrow via Zoom, please tell me exactly what text should go on what page of the website.

**Comment by MomoMoses** [comment]
Ack! It was the first page only! I literally did not see that there was a second page.
[this is the one!](https://uchicago.box.com/s/jj8qfjjrhfh3xcezr8de8jhry1me3o9x) I've removed extraneous.

**Comment by johnjung** [comment]
This is now implemented in https://github.com/johnjung/bmrcportal/commit/fe67e313a6ce39866b932e21156921cb7acbf839 and live on the server.

**Comment by MomoMoses** [comment]
new Curated Topic "Womanism" to be added.

**Comment by MomoMoses** [comment]
Content for additional topics, including "Womanism" by Marcia and 3 new topics from IIT's Mindy Pugh will be added post-integration into Wagtail.
