### ISSUE TITLE
Blank documents appear in search results

### ISSUE THREAD

**Issue by johnjung** [johnjung/bmrcportal#2]
To demonstrate the problem, do an empty search (/search/). The top two search results don't have any metadata in an alpha A-Z sort.

**Comment by johnjung** [comment]
Two test documents were causing this. I deleted the documents and did a review of the code to confirm that there aren't any references to them. I deleted all documents in the DB and reloaded them. This should be fixed.

**Comment by MomoMoses** [comment]
Confirmed 8/20 - LLM
