### ISSUE TITLE
Sidebar term clickability

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#20]
The sidebar facet does not allow you to click the same term several times -- if it is already selected, it appears as a non-clickable term in the LH sidebar.
While the terms above the results are obviously the selected terms -- they are highlighted in green -- these terms in the sidebar appear in only a slightly different color. Perhaps they could be italic or in a color that is more highly contrasting with the color of text for terms that are available to be selected.

**Comment by johnjung** [comment]
To keep UI decisions consistent, consider https://github.com/johnjung/bmrcportal/issues/14 alongside this issue.

Do we have a mockup that shows how selected terms should appear in the sidebar?

**Comment by johnjung** [comment]
See https://uchicago.app.box.com/file/809484753142?s=3to0b6hcuhyuwsfnoqv9jazdi3hl96nm.

**Comment by MomoMoses** [comment]
Link above shows "Archives" in the LH sidebar as a "Browse by" visibility issue, #58 (issue closed, solve here).

Here is the mockup of the SERP with a selected facet item from Topics.
[https://uchicago.app.box.com/file/805384713062?s=iq4yjs5ymxbhqvd5kix0zynt22skqu3h](url)

**Comment by johnjung** [comment]
Thanks very much. This is now fixed in https://github.com/johnjung/bmrcportal/commit/bc7f3b12ba1b83ab9318e0f4ba84bca4a1528ced, and it's live on the site. I'm closing this issue out, please re-open if necessary.
