### ISSUE TITLE
Explore visual separation of elements

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#22]
There are several instances where there may need to be more of a visual separation. The "cost" of this in terms of clarity vs. clutter and in terms of window space would need to be considered and balanced.
1. On the SERP, the facets sidebar could separate the facet lists. Perhaps the header labels could be slightly larger?
2. On the SERP, is the separation between collection results satisfactory?
3. On the SERP sidebar, should "View more [facet]" look different than a term? (These are clickable text with very different functions but identical appearance.)
4. On the SERP, after clicking "View more [facet]," should "View all relevant [facet]" look different than the "View less [facet]" text? 
5. Consider the visual display of elements on the home page using various devices and screen sizes and decide about vertical spacing. Is it open enough, takes up right amount of vertical space, etc.? [I know this is usually already on the list, but just to make sure we decide explicitly about this.]
#DESIGN

**Comment by MomoMoses** [comment]
For reference, here's the mockup Kathy did of the [SERP with a selected facet](https://uchicago.app.box.com/file/805384713062?s=iq4yjs5ymxbhqvd5kix0zynt22skqu3h)

**Comment by MomoMoses** [comment]
For further reference, here's the [home page mockup](https://uchicago.box.com/s/mtv1s2kqnk5x0bhrntkt228nnisxde5p)

**Comment by johnjung** [comment]
I implemented some changes in https://github.com/johnjung/bmrcportal/commit/d1164f693c1dbce47e7637347c79ab5e6df8d2db that are now live on the server.

Facet labels are now slightly larger, and "view more", "view less" and "view all" facet links are now italic, to match the mockup. I'm going to tag this issue as "review" so I know to return to it to check on spacing issues later on- because spacing involves all of the elements on the page, ongoing changes to elements can have an effect on the spacing in general.

**Comment by MomoMoses** [comment]
I like the "view ..." links as italic, much clearer.
Let's hold to review and check on the overall spacing, as you suggest, once we've got the other elements done for Phase One.

**Comment by johnjung** [comment]
As per our Zoom conversation, it's ok to hold off on this until the February launch.

**Comment by MomoMoses** [comment]
Have you reviewed this, however informally, or on an as-you-go basis? How might a review like this best be organized? 
This can be done in Spring, with a structure in place. I'd like to do a quick review for anything glaring however.
