### ISSUE TITLE
SERP archive links

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#23]
to demonstrate the issue, choose Browse by Archives from the home page. At the bottom of each SERP snippet, your chosen archive will be listed. If clicked, nothing happens, even though it appears as a link.

This link should go somewhere! It could link to the repository's archives/special collections page or a page on the portal or BMRC site with information about member institutions (if applicable). May be best to duplicate the link destination that is planned for the "Archive Info" box that will appear on the sidebar of finding aids.

**Comment by johnjung** [comment]
Ok. I'm going to bring back the "content" tag on this one- when you have that information for each institution please let me know. Then I'll add it to the left sidebar and hook this up.

**Comment by MomoMoses** [comment]
Student worker starting this week (10/11) - will assign this task.

**Comment by MomoMoses** [comment]
This should definitely hold until Phase Two, and more user research.
