### ISSUE TITLE
Bad source data?: Section and subsections not properly nested

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#30]
Guide to the ACLU Illinois Division, UChicago, is the example. [https://bmrcportal-test.lib.uchicago.edu/view/?id=BMRC.UOC.ACLU_IL.xml](url)

The SECTION is called "INFORMATION ON USE" which has 8 subsections. Only the first two pertain to use: Access and Citation. Oddly, the actual use element in EAD <userestrict> Conditions Governing Use, does not appear at all here.

Not in the right hierarchical position: Processing Information note, Historical Note, Scope Note (which is actually a note on the Arrangement), Related Resources, Subject Headings, Terms added by the BMRC Team.

**Comment by johnjung** [comment]
This looks like a source data issue to me too. I'm going to tag these "data" so we can keep track of them.

**Comment by MomoMoses** [comment]
[https://www.lib.uchicago.edu/e/scrc/findingaids/view.php?eadid=ICU.SPCL.ACLUIL](url)
Except that it might not be  -- I looked for the collection on the UChicago SCRC site and it appears properly nested. I thought we used their EAD straight up, but I'll check. I like how the Series and Subseries appear here.
