### ISSUE TITLE
Fix lack of spacing and make line breaks between subject terms in finding aid (controlaccess tag)

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#4]
To demonstrate the problem, go to an example finding aid: https://bmrcportal-test.lib.uchicago.edu/view/?id=BMRC.HWLC.ENGLEWOOD.xml and scroll down to the control access or subject heading section. On the line beginning with "African Americans" several of the terms are on one line in a run-on manner with no space or line in-between. They are linked, which is the expected appearance and behavior.
[Could be a data or front end issue.]

**Comment by johnjung** [comment]
This should be fixed in https://github.com/johnjung/bmrcportal/commit/ca5e0e3a2ca2565bccf3fff10227194b9eab3aef. This has been pushed to bmrcportal-test.lib, please take a look.

**Comment by MomoMoses** [comment]
I think the bulleted format works. To be discussed with Kathy. (Missing header is another issue.)
