### ISSUE TITLE
Make sure all informational links are specific

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#40]
Need to add this decision to the content guide. Example: member spotlight on index page. "Here" and "view collections at ..."

**Comment by MomoMoses** [comment]
This was included with the list of repositories, links (URLs) to go to, physical address, and link text to use for enhanced accessibility and specificity.

**Comment by johnjung** [comment]
That's great. In that case this issue appears to be covered by https://github.com/johnjung/bmrcportal/issues/56. I'm going to close this out, please re-open if necessary.
