### ISSUE TITLE
fix the styling of abstract elements in the descriptive overview

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#44]
[https://bmrcportal-test.lib.uchicago.edu/view/?id=BMRC.HARSH.HARRIS.xml](url)

Coding the `<abstract>` tag as a nested sub-element of Descriptive Overview is causing it to be styled in a way that is not visually consistent or logical.

Even if the data doesn't put "Abstract" on the same level as "Descriptive Overview" they should appear as if they are. Large all caps, reddish color, different font styling. As a side benefit, if Abstract is placed as a major content item after the Overview content, the "Language of Materials" will move up and be displayed within the overview elements, which is logically where it belongs.

**Comment by MomoMoses** [comment]
I like option 2, and it also seems simpler. Bonus!

**Comment by johnjung** [comment]
Sounds good. I changed the title of this issue, I'll get to this soon.
