### ISSUE TITLE
Inventory lists don't need to use the labels "Title" or "Note" 

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#46]
Checking out the Durham collection [https://bmrcportal-test.lib.uchicago.edu/view/?id=BMRC.HARSH.DURHAM.xml](url) there is an issue about the inventory lists. To save space, let's not label the titles of folders or the descriptive notes that are added. These are probably in the XML, but the information is understandable without the label. (The cut and paste does't really show the amount of space taken up in the display.)

Box 1        Folder 8            Title
                                             U.G. Dailey and Daniel Hale Williams, 8/8/48
                                         Note
                                             Script for "The Heart of Geo. Cotton," The S

**Comment by johnjung** [comment]
Thanks very much, Kathy and Laurie. 

In https://github.com/johnjung/bmrcportal/issues/49, we started displaying the labels in the descriptive summary at the top of each finding aid next to their values. Is that appropriate here too? (If so, it solves the indentation problem I mentioned above.)

(Please note that changes here may impact https://github.com/johnjung/bmrcportal/issues/35.)

**Comment by MomoMoses** [comment]
My thought was to drop the labels here altogether. It's pretty obvious that there are "Dates" and if there's a line describing contents, we don't need to see "Title".

**Comment by johnjung** [comment]
It's easy enough to remove all of the labels from that part of the inventory- but it seems to me that they're useful in cases where each `<did>` has more child elements, or where the child elements might not be as easy to tell apart. Here is an example, where lots of those elements contain a size, title and note:

[https://bmrcportal-test.lib.uchicago.edu/view/?id=BMRC.DEFENDER.INDIVIDUALS.xml](https://bmrcportal-test.lib.uchicago.edu/view/?id=BMRC.DEFENDER.INDIVIDUALS.xml)

What do you think?

**Comment by MomoMoses** [comment]
This is quite an outlier, so hard to know if it's necessary to have labels. Can we just let go of them for now and bring them back later should user research warrant?

**Comment by johnjung** [comment]
This is now implemented in https://github.com/johnjung/bmrcportal/commit/214054fad87186f623c22459cb736481bf9c5bbb and live on the site. Please take a look and let me know what you think, if it looks good we can close this issue out.

**Comment by MomoMoses** [comment]
Looks great. Very clean.😃🥳
