### ISSUE TITLE
Save space at top of finding aid by limiting Repository information to the name only

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#48]
[https://bmrcportal-test.lib.uchicago.edu/view/?id=BMRC.HARSH.DURHAM.xml](url)
The Descriptive Summary includes information about the repository. Many finding aids only list the name of the institution. This is preferable to the duplicative and long version in this document.
The address will be included in the LH sidebar with repository information anyway, so it's not needed at the top of the document too.

**Comment by johnjung** [comment]
This is now fixed in https://github.com/johnjung/bmrcportal/commit/8a2353954179dfed78e8a7c89e5ac77809cc3501, and live on the server. I'm going to close this issue out, please re-open if necessary.
