### ISSUE TITLE
Listing of Descriptive Summary elements takes up a lot of lines

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#49]
The element name is on one line, with the content value on the next one. Since there may be several elements included here, it can end up taking up a lot of space. 
One solution would be to arrange it with the element name, colon, content value all on one line.

Title: Richard Durham Papers
Dates: 1939-1999
etc.

#design

**Comment by MomoMoses** [comment]
[https://uchicago.app.box.com/file/807084219878?s=86ze2stummldz0bma0ek278dl9k7nphr](url)

Finding aid mockup shows these overview elements with label and text value side by side.
Label is in italics.

I like the red text styling you have created for the section labels vs. these lower case. I don't think it's a visibility problem, but we could ask.

**Comment by johnjung** [comment]
This change is in https://github.com/johnjung/bmrcportal/commit/881a62c71c6f1f4f3f412c64bd1056bc51a601a1, and this is now live on the server. I'm going to close this issue out, please re-open if necessary.
