### ISSUE TITLE
include archive logo, address and contact link in finding aid viewer and archive browse

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#56]
To demonstrate, choose Browse Archives from the home page. Select an archives, for example, the Harsh. The selected facet appears at the top of a results list for all collections from that archives.

Here is the mockup version of the page: [https://uchicago.box.com/s/1laay3kuo5q9vdo6olbyid0991hyahea](url)

At the top of the results list is a banner or content box going across with information about the repository -- this is a nice feature! the information and design appear in a smaller version in the sidebar of a finding aid.
![image](https://user-images.githubusercontent.com/3534298/138355235-369241a0-6c75-4fa4-a677-a9b5c7ad05eb.png)

**Comment by MomoMoses** [comment]
https://uchicago.box.com/s/nk2rkbnqe34tzd17mwfp9ntlhmtklmom

**Comment by MomoMoses** [comment]
some may be missing; I'll have the student worker take a look next week.

**Comment by MomoMoses** [comment]
Spertus uses the ampersand.
Leave off the (CYC).
Vivian G. Harsh Research Collection, Woodson Regional

**Comment by johnjung** [comment]
This information should also appear in the sidebar of the finding aid viewer- see [this mockup](https://uchicago.app.box.com/file/807084219878?s=86ze2stummldz0bma0ek278dl9k7nphr).

**Comment by johnjung** [comment]
This is now implemented in https://github.com/johnjung/bmrcportal/commit/b941c766c18001885b3cb356b36ccf778bf624a4 and live on the server. Please take a look when you have a chance- there are still some archives missing logos, so if you'd like me to keep this open and tag it as "data" just let me know. 

Also, please note: adding repository information to the finding aid viewer sidebar increased the width of the sidebar in lots of cases. I'm going to deal with that issue in https://github.com/johnjung/bmrcportal/issues/51.

**Comment by MomoMoses** [comment]
Yes, do keep open as "data" -- I'll ask Warren to check on that this afternoon after 1pm.
Yes, the width is nuts!
I had thought perhaps it could be contained within a separate content block of some kind and styled differently so it wraps. Logo might be too large... thoughts? Not sure we specified this!!!

**Comment by johnjung** [comment]
In issue #51 I'll probably constrain the width of the logo to about 60% of the width of the sidebar to get it to match [the mockup](https://uchicago.app.box.com/file/807084219878?s=86ze2stummldz0bma0ek278dl9k7nphr), and I'll figure out something appropriate for mobile too. Some of the logos are relatively low resolution- you might want to get higher-resolution versions to keep them from upsampling.

**Comment by MomoMoses** [comment]
This looks good!👌

**Comment by MomoMoses** [comment]
Can you kindly take note of the ones that are lo-res? We'll ask the
institutions for better ones.
