### ISSUE TITLE
"Clear facets" link or button needed at top of a SERP page list

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#57]
[https://uchicago.app.box.com/file/809486923260?s=1laay3kuo5q9vdo6olbyid0991hyahea](url)
This mock included a link to clear all facets in one go. Could be useful. Don't know if this is feature-creep or if it's difficult to implement or not. Not an emergency -- could be good to check this with #research.

**Comment by johnjung** [comment]
This is now implemented in https://github.com/johnjung/bmrcportal/commit/b9042c9d8f6671153d1a4cd371758fcdc2d056e7, and live on the server. Please take a look and let me know if this is working the way you'd expect it to.

**Comment by MomoMoses** [comment]
looks good!
