### ISSUE TITLE
All Archives, e.g.: Need more visual cues that the Facet was selected

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#58]
[https://bmrcportal-test.lib.uchicago.edu/browse/?b=archives](url)
 
Choose "Archives" from the Browse menu. The LH sidebar lists all the Browse facets, plus a featured curated topic.
It's not visually clear what has been chosen for the Browse display, as the word is slightly dimmer, and can't be clicked. In our mockup it was set at a strong italic.
[https://uchicago.app.box.com/file/809484753142?s=3to0b6hcuhyuwsfnoqv9jazdi3hl96nm](url)

**Comment by johnjung** [comment]
This appears to be a duplicate of https://github.com/johnjung/bmrcportal/issues/20. Can we close this issue and solve it there?

**Comment by MomoMoses** [comment]
Ok to close and solve in #20.
