### ISSUE TITLE
Shuffle sort does not allow repeated shuffles

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#6]
To demonstrate the issue, first do an empty search using the search box. The display defaults to an A-Z sort, which is correctly highlighted, since relevance has no meaning where there are no terms. Click on "Shuffle" to get randomly re-sorted results listing. Click again on Shuffle to get a new random sort, and nothing happens.

This same limitation holds for viewing a Browse by [facet] page. Only one Shuffle is effective. Spec is to allow for a new Shuffle every time it is clicked.

**Comment by johnjung** [comment]
This is fixed in https://github.com/johnjung/bmrcportal/commit/f110631e4c8c9847630d4a225851a6b080dabfd4, I'll push this to bmrcportal-test.lib soon.

**Comment by johnjung** [comment]
This is now live on bmrcportal-test.lib. Please take a look and I'll close this issue out.

**Comment by MomoMoses** [comment]
Looks like it's working for empty search results and for browses.

**Comment by johnjung** [comment]
That's great. I'm going to close this issue out, please feel free to re-open it if necessary.
