### ISSUE TITLE
Meaningful (non-opaque) repeatable anchor links

### ISSUE THREAD

**Issue by johnjung** [johnjung/bmrcportal#66]
There is an underlying issue I'd like to look at before https://github.com/johnjung/bmrcportal/issues/54: 

For an example, see the URL "https://bmrcportal-test.lib.uchicago.edu/view/?id=BMRC.DUSABLE.LOCHARD.xml#idp34715520". At the end of this URL there is an anchor link ID "idp34715520".

Our transform generates these IDs each time the transform is run. Right now they're different every time the transform runs, but I'd like to get them to be consistent across transforms so users can bookmark them. Beyond that I think it may be better if they're not opaque- right now they're mostly a random sequence of numbers,  but it seems to me that anchors like "descriptive-summary", "scope-and-content-note-2" would be more useful. 

Could you include a link to the best list of other finding aid interfaces we have so I can see what other people are doing? 

Additionally, if you have feedback on this specific change please let me know. I'm assuming that meaningful anchor links are better, but if there are other things to think about here let me know- and definitely let me know if you have preferences for the style of anchors that works best.

**Comment by johnjung** [comment]
This is now fixed in https://github.com/johnjung/bmrcportal/commit/4b90b79e2619ad581429163d25a5cb4964192e3b, and live on the server. Please take a look and let me know what you think. If this is ok we can close this issue out.

I implemented this quickly using the name of the parent element for the anchor- e.g. "scopecontent", "scopecontent-2", "bioghist", "bioghist-2", etc. I think it would be a little friendlier to use the link text itself to make the anchors, but it's a bit more complicated to code that. If it seems like that would be a nice enhancement we can always tag it as "enhancement" and try to set it up sometime in the future.

**Comment by MomoMoses** [comment]
This looks good john. Ok to close with a note to review and revisit later.
