### ISSUE TITLE
Shuffle facet feature needs associated design snippet to be displayed

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#67]
On the home page, the rightmost feature displays a random item from every facet except "Archives." Each facet will have an associated design scrap to be displayed in the content background area.
Design scraps are on Box. [https://uchicago.app.box.com/folder/136040753332](url)

Need to assign a scrap to each facet:
1. Topics = banner-green [https://uchicago.app.box.com/file/802412529853](url)
2. People = navy+green [https://uchicago.box.com/s/vti41847big0izxuuoita76ngdkin0mq](url)
3. Organizations = banner-brwn [https://uchicago.app.box.com/file/802413670750](url)
4. Places = banner-navy [https://uchicago.app.box.com/file/802412438420](url)
5. Decades = banner-red [https://uchicago.app.box.com/file/802412529104](url)

#design plus coding to associate the image with the facet

**Comment by MomoMoses** [comment]
Graphic design needs to be used here definitely -- AND tying the display of the random facet with its associated design scrap needs to be done. Coding!

**Comment by johnjung** [comment]
Do we have a mockup that shows this in context? Alternatively, if this graphic design approach was borrowed from another site, could I see what it looks like there? (I need to figure out how those patterns should stretch or repeat to fill their space.)

**Comment by MomoMoses** [comment]
No this was something I cooked up! The image should be sized to the square for the random feature block, which won't change. I think repeat for viewport re-sizing should work. These designs are from Chelsea -- she may be able to weigh in on this as well.

Mockup is here: [https://uchicago.box.com/s/mtv1s2kqnk5x0bhrntkt228nnisxde5p](url)

**Comment by johnjung** [comment]
This is now implemented in https://github.com/johnjung/bmrcportal/commit/93ef09bbdd819e7f831bb9e2810a494078eda43f, and live on the server. Please take a look at how this looks and let me know what you think.

**Comment by MomoMoses** [comment]
This looks great! I'll run it by the original designer to see if she'd like to tweak the design "scraps" at all. :)

**Comment by johnjung** [comment]
Sounds good. I'm going to close this one out, but please feel free to re-open if I can make any changes.
