### ISSUE TITLE
Check contrast/approach for selected page numbers and sorting method 

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#68]
The mockup shows a dark blue rectangular background color with white text for selected pages. Unselected pages are outlined in solid light gray, black text. Unselected sort link texts are the same blue as the background used to highlight selected pages. Same display for selected sort method as for selected page.
[https://uchicago.app.box.com/file/805386534908?s=rmtuhvgdr39yhisbbrxjimmt528mx07l](url)

The current display grays out the page selection. Is this enough for accessibility? Selected sorting method e.g. "A-Z" has a light blue background, dark blue text. Hover shows and darkens the background. Sorting method names are not underlined.

However "Next page" button is underlined in addition to showing the blue background and blue text on hover. Should be consistent with pagination displays.

#DESIGN

**Comment by kzadrozny** [comment]
Heads-up that the button and link colors are a bit different on the test server than they are on the mock: https://bmrcportal-test.lib.uchicago.edu/search/?q=hampton
These can easily be tweaked and contrast checking can be an automated check using WAVE. David is taking over web ADA items; you can always ask him to do a review once the portal is complete and he can run WAVE checks on everything.

**Comment by MomoMoses** [comment]
Thanks, Kathy! We should definitely do a WAVE check as an "almost done" step.
:)

**Comment by johnjung** [comment]
I'm going to close this out, since https://github.com/johnjung/bmrcportal/issues/81 covers WAVE testing.
