### ISSUE TITLE
Breadcrumbs do not lead back to SERP from Finding Aid page

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#7]
To demonstrate the issue, do an empty search, then select facet term(s). From this SERP, choose a collection to view the finding aid. From here the breadcrumbs lead only to the "Collections Portal" index page or to the BMRC main page.
The browser "back" button does go back to the SERP.

**Comment by johnjung** [comment]
The current behavior is how I understood the spec. Currently, breadcrumbs on the site do not reflect the the path that a user took to get to a specific page, instead they reflect the information architecture of the site in a static, non-interactive way. (So in this case, a user needs to click the back button to get back to a search result page.)

It would be possible to implement a breadcrumb link leading back to the SERP, but this would be a new feature. If we really need this could we save it for a v2.0?

**Comment by MomoMoses** [comment]
We had discussed this and I understand the user path vs. architecture distinction. What's perhaps surprising is that a SERP is not actually part of the information architecture. Is that correct?
Agreed to see if this is needed through user research, and push it to 2.0 if at all.

**Comment by johnjung** [comment]
The fact that SERPs are dynamic is the issue- so if we need a "back to search results" link, I would need to implement something to save the state of the SERP, which we're not doing right now. I'm going to close the issue out, but if we need to revisit this we can open it again.
