### ISSUE TITLE
TOC links jump to a line well below the heading and indicated section

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#70]
From the LH sidebar in a finding aid, clicking on any item in the TOC tends to pop the page to a place that is below the heading for the TOC item clicked. It's sometimes hard to tell where you are exactly and where the desired content can be found from the beginning.

**Comment by johnjung** [comment]
This is now fixed in https://github.com/johnjung/bmrcportal/commit/1ab5fc842c54ed38ea03d05fac8468316fc08211, and live on the server. I'm going to close this issue out, please re-open if necessary.

**Comment by MomoMoses** [comment]
Looking good! :)
