### ISSUE TITLE
Logo and thumbnail sizing 

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#72]
Would recommend a thumbnail size that is between 150px - 300px in width. This is the sweet spot for having a readable image that doesn't take up too much space. You can leverage the Bulma responsive image classes to get what you want: https://bulma.io/documentation/elements/image/

_Originally posted by @kzadrozny in https://github.com/johnjung/bmrcportal/issues/12#issuecomment-954898183_

**Comment by johnjung** [comment]
I'll keep this in mind, but I'd like to close this standalone issue out. If you'd like to make a note of this on the specific issues where it's relevant please do.

**Comment by MomoMoses** [comment]
That's fine; I'll note it on the individual issues.
