### ISSUE TITLE
curated topic feature edits

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#74]
We have a [photo image](https://uchicago.box.com/s/mg0g42mjjhu64alk9hgc1i44dv1q2w6i) for the featured topic example in hand, which is "Black Studies." There will also need to be a spot for the photo caption, the image URL, and the preferred citation (for the image).

See again the [mockup/sample page in Box](https://uchicago.app.box.com/file/871367797691?s=3rhunvf7l1iml2olktpz5gp413i0uuyu).

I'm curious about how this will be wired up to display a new entry each week from a pool of content that is stored ... where?

**Comment by johnjung** [comment]
For the Flask-based site, the content for curated topics is stored in a configuration file that is not checked into git. The data for the first topic looks like this:

`CURATED_TOPICS = [ 
    {   
        'title': 'Black Nurses',
        'introductory_text': 'Advocacy for Black Studies (also known as African American Studies or Africana Studies) programs and departments at higher education institutions emerged from the Civil Rights Movement and Black Power Movement of the 1960s. Black students at historically Black Colleges and Universities (HBCUs) and predominately white institutions typically organized protests for institutional change, among these, the inclusion of Black history in their education, resistance to traditional, Euro-centric curriculum. By 1971, more than 500 programs and departments were established in the United States, including at the University of Illinois Chicago (1971), Loyola University Chicago (1971), and Northwestern University (1972).',
        'img_caption': 'The FMO Press Conference held to announce FMO’s boycott of the new African American Studies Department, November 29, 1972. Citation: Northwestern University Archives, Ronald Craig Photographs',
        'img_src': 'http://placekitten.com/200/300',
        'search_url': '/search/?q=black+studies' 
    }       
]`

Once we migrate to Wagtail, these fields will be editable in the GUI in the admin.

**Comment by MomoMoses** [comment]
> { 'title': 'Black Nurses',

This is great to know, thanks so much. Can you change that first data element to 'Black Studies'?

**Comment by johnjung** [comment]
Yes, I saw that afterwards- it's already changed on the server. This is now implemented in https://github.com/johnjung/bmrcportal/commit/aca7490f6d33feae442646591f577ebca6ca9bd8 and live on the server, I'm going to close this issue out, please re-open if necessary.

**Comment by johnjung** [comment]
[This example](https://uchicago.app.box.com/file/871367797691?s=3rhunvf7l1iml2olktpz5gp413i0uuyu) includes an author byline- I'm going to add this to the curated topic data structure and display authors on curated topic pages.

**Comment by MomoMoses** [comment]
Thanks!

**Comment by johnjung** [comment]
Bylines are now added in https://github.com/johnjung/bmrcportal/commit/804741c069fa929183fbf1a3bedea1cfe470e1fa and visible on the test site.

**Comment by MomoMoses** [comment]
Instead of the lorem ipsum text at the bottom of the featured topic, put this:
The BMRC’s **Curated Topics** list is designed to help remedy the pervasive invisibility of primary source material documenting Black history and culture. In development now, it will be a special vocabulary that concisely encapsulates the subject domain as a dynamic body of knowledge. Like having a subject matter expert at your elbow! If you’d like to be a part of developing this resource, email the Project Archivist at lmoses@uchicago.edu

**Comment by johnjung** [comment]
The text above is different from the text in [Home Page Content+CTL 2021-12-06.docx ](https://uchicago.app.box.com/s/74j5308m1tfaj0ccose28mbqkpakoejq), which you reference in https://github.com/johnjung/bmrcportal/issues/92. Both the comment above and the spec are dated 12/6. I'm assuming that the Word doc is definitive, but if it isn't, please update that document with the text above and I'll update the site. 

I'm going to close this issue out, please re-open if necessary.

**Comment by MomoMoses** [comment]
This text is for the FEATURED topic page only, which is now "Black Studies." Sorry for the confusion here. I felt it was important to replace the "lorem ipsum."

**Comment by johnjung** [comment]
Ok, got it- thank you. This is now updated in https://github.com/johnjung/bmrcportal/commit/8da73717cf918742465ef89945bc820190ef67bc and live on the site. Please take a look and if it's ok, please close this issue out.

**Comment by MomoMoses** [comment]
Perfect!
