### ISSUE TITLE
more explanatory text - labels, short descriptions

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#75]
I think we should take more of a cue from the [current page on the BMRC site](https://bmrc.lib.uchicago.edu/collections/) that has a large search bar and introduces the collections database -- the beta new Portal is a bit too sparse and therefore can be vague, hard to grasp the functions.

Center features may need designed large labels about what they are: Curated Topic | Online Exhibit | Featured Facet.

Random feature may need a tagline or intro, like Try a Facet or Surprise Facet or Try this! Chance | Lottery

**Comment by johnjung** [comment]
Changing the size and position of the search bar would require a redesign of the portal homepage- If that's what you'd like to do, please be aware that this will push all current project deadlines back, because it would create a new iteration of mockups, sign-off, implementation and testing.

Alternatively, we could launch the site according to our current specifications, and you could do user testing to determine how useful these features might be. At this stage in the project, to me this makes the most sense. 

I'm going to close this issue out, but if you'd like to proceed with a redesign please be sure to get approval from Charles and Elisabeth on the additional work.

**Comment by MomoMoses** [comment]
Nope, no need to change the size and position of the search bar! That part is fine.

I was wondering if I could add more explanatory text, mostly. What can I do WITHOUT triggering a redesign and all of that? (I believe I was not clear on the extent of this idea.) The issue title is the basic idea -- text, labels.

Here's what could be helpful:
1. Tagline with heading "The BMRC Collections Portal -- cool and informative tagline"
2. More explanatory vs. marketing style text for the paragraph below heading. How many lines are available that keep the feature blocks visible?
3. Text labels (with alt text attributes) that look "designed" to indicate better what each feature is all about, especially the random feature, so that people know better what to expect when they click on it

this brief textual system isn't always the best for clarity of intent! :(

**Comment by MomoMoses** [comment]
Prompt inside the search box: "Search member collections"

**Comment by MomoMoses** [comment]
What are your thoughts, if any, about a text label/caption above or below the search bar? Is that old hat? Clutter?

**Comment by johnjung** [comment]
Giving the portal a name at this point is a pretty big change- I recommend against this just before the launch, especially if stakeholders who have seen the previous mockups haven't voted on the name.

Please let me know if the project stakeholders are in favor of the name change- in that case it's easy enough to change the heading that currently reads "THE BMRC COLLECTIONS PORTAL" to the bold text above. Changing the paragraph below that is also not a problem. I'm assuming that the about link should lead to https://bmrcportal-test.lib.uchicago.edu/about/ and the help link should lead to https://bmrcportal-test.lib.uchicago.edu/help/. Please note that those pages are still awaiting content.

Changing the text inside the search box from "search collections" to "search member collections" is not a problem in any case. 

I recommend against putting any extra labels above or below the search bar, unless they solve a demonstrated problem.

Please let me know what you think, and I'll make whatever changes make sense.

**Comment by MomoMoses** [comment]
The name is part of the deliverable -- Marcia and I came up with a strategy for this. I'll talk about it with you this afternoon.

**Comment by johnjung** [comment]
[This change](https://github.com/johnjung/bmrcportal/commit/790cf13b11725554128c345d4486519e87ae0ad3) is now live on the bmrcportal-test server. Please take a look and let me know what you think.

**Comment by MomoMoses** [comment]
Let's leave it for now, but next week, I will solidify and get feedback about the name, how to present the "what it is" with simple heading and/or tagline, and the text underneath.

#content

**Comment by MomoMoses** [comment]
Looking at "try a term" and "surprise search" for an overlay label for the random feature. Still think it needs something ...
#research

**Comment by MomoMoses** [comment]
No name for now. Updated narrative content is in review. Holding off on idea of label for random term feature, if a sentence describing the features can be included in the brief descriptive narrative at the top of the page.

**Comment by MomoMoses** [comment]
This text was sent round to the team for their feedback and approval:
### The BMRC Collections Portal 
Your gateway to the Black Metropolis in Chicago and beyond 

Discover the unique collections on Black experiences freely available to you in libraries, museums, archives, and other organizations in the Chicago area. Choose your path: search member institutions’ collections with keywords, browse a facet, like People or Topics, or click on one of the boxes below: Curated Topic, online exhibit, or the “Try a Term” feature. Learn more about the project or consult our Research Help.

**Comment by MomoMoses** [comment]
The second line is a tagline that can be next to the headline separated by a dash, OR formatted as a sub-head/tagline in the line underneath the headline.

**Comment by MomoMoses** [comment]
Thanks for the heads up - doh!

**Comment by johnjung** [comment]
I'm closing this bug out, please re-open if necessary.
