### ISSUE TITLE
Top menu bar: window re-size truncates menu item

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#76]
The top menu bar that replicates the current BMRC site lists these menu items: 
Search Collections | Programs | News | About | Resources | Contact | Support us

If window is reduced in size, "Search Collections" becomes "Collections" which is a bit misleading. Can it put a word on a new line below? The others don't truncate but they are short! The window has to be re-sized fairly large to get the word "Search" back. Perhaps it could truncate to "Search" instead -- also misleading but it doesn't amplify the common error where people assume that the BMRC is a repository!

**Comment by johnjung** [comment]
(I'm going to close this one out here, but please feel free to reopen it on the bmrc repo.)
