### ISSUE TITLE
Expand link for the About the Portal page on the Index page to include the word "about" 

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#8]
On the Index page, there is a short descriptive line, with a link to go learn more about the Portal project itself. For accessibility purposes, it may be best to include the word "about" in the linked text. The new linked text would be: "about the Portal" rather than just "the Portal".

**Comment by johnjung** [comment]
This is fixed in https://github.com/johnjung/bmrcportal/commit/b4493408e03824baaa35fe67b822220d1e14db06, I'll push this change to bmrcportal-test soon.

**Comment by johnjung** [comment]
This change is now live on bmrcportal-test.lib. I'm doing to close this issue out.
