### ISSUE TITLE
too many line spaces in TOC between summary elements and inventory

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#80]

**Comment by johnjung** [comment]
I updated the CSS in https://github.com/johnjung/bmrcportal/commit/8e1b806ce0e4125119837c0d1d5e3791dde2abce. This change is now live on the site. If this doesn't fix the issue, please let me know. (Also, please provide a sample URL so I know we're looking at the same thing.)

**Comment by johnjung** [comment]
Closing as per our email exchange.
