### ISSUE TITLE
Re-visit design of "Browse by" nav bar on home page

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#88]
The text inside a color block looks suspiciously like a button, but "Browse by" isn't actually clickable -- it's the facet terms that are.

Also the behavior of this color background and the nav bar is confusing as window sizes change.

#design

**Comment by johnjung** [comment]
This is present in [the mockup](https://uchicago.app.box.com/file/805384943051?s=mtv1s2kqnk5x0bhrntkt228nnisxde5p)- I'm going to tag this as "research" so you can user test this if you'd like.

**Comment by MomoMoses** [comment]
Ok, though I'd rather tag it #design. I'm not crazy about its appearance. Also the behavior is weird. The CSS might need tweaking a bit.

**Comment by johnjung** [comment]
Because this aspect of the design is clear in the mockup, changing it is out of scope- and we really do have a lot to do already for both phase one and phase two. I'll switch the label to "enhancement" so we can continue to track this.

**Comment by MomoMoses** [comment]
Sounds good!
