### ISSUE TITLE
digital exhibit sample page for soft launch

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#89]
The teaser content block is in place on the home page for the Portal with a placeholder (kitty) image. Need a few things to make this work for soft launch.
1. photo to use in content block on home page
2. title for exhibit - on exhibit page and on content block on home page
3. mockup for exhibit page
4. sample and placeholder content for the exhibit page
5. explanation text that this is "coming soon" as a work in progress on the theme
6. links to several finding aids that help explore the theme

**Comment by MomoMoses** [comment]
Title for now for middle feature block: Black Artists and Designers
Simple!
UIC and CHM have a line on some digital images for me. We will choose one to populate the home page feature block.
If we have several we can do a gallery page with minimal text for the prototypical exhibit placeholder, explaining what's coming next.

**Comment by MomoMoses** [comment]
obtain image from Charles Harrison collection at UIC and add for feature block

**Comment by MomoMoses** [comment]
let's use the [record player](https://uchicago.box.com/s/uqjquwgspxwzot8x5i06n3z3ux605lcx) for the home page content block.
can we put this one and the [toaster](https://uchicago.box.com/s/gu0k4vzavku12tiffvsc8t77bb60l3of) on the teaser exhibit page for the Black Artists and Designers? with the link to the [CARLI site](https://collections.carli.illinois.edu/digital/collection/uic_des)

This text should be on the teaser exhibit page:
Images courtesy of the Charles Harrison Design Collection (University of Illinois Chicago). Explore the full exhibit online at [CARLI digital collections](https://collections.carli.illinois.edu/digital/collection/uic_des).

**Comment by johnjung** [comment]
This is partially implemented in https://github.com/johnjung/bmrcportal/commit/5365b554374966ccc9062c6ec722ed6351e041d1 and now live on the site. I'm tagging the rest of this issue for phase 2- is it possible for us to get higher resolution source images for exhibit pages?

**Comment by MomoMoses** [comment]
Content is mocked up in main BMRC site to explore what content types need to be added to the Wagtail admin toolkit. 
Embedding video is automatic now but not working in at least one case. Resolve, to be done later, as needed.
Embedding audio content. To be done later, as needed.
**Gallery style display - uniform size images in a grid** Nice to have as soon as practical.
Timeline.js - has been implemented on other UChicago exhibit. To be done later, as needed.

**Comment by MomoMoses** [comment]
Expanded content type options has been implemented for Exhibit main pages and child pages of Exhibit main page.
Timeline.js may need additional help to implement as needed later.
Bug for embedding video is being investigated.

**Comment by MomoMoses** [comment]
I believe that the source of this issue has been discovered and resolved. Another issue was opened for embedding video. Certain Rich Text boxes are not actually Streamfields. Video works fine if used in a bona fide Streamfield Rich Text box.

**Comment by MomoMoses** [comment]
I think we have in place what we're going to be able to manage for this launch, Feb 2022. 
May be able to tweak or add other features for exhibits later in the year.
