### ISSUE TITLE
pagination buttons should match existing BMRC site

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#90]
The pagination buttons on the SERP page have an outline, a white background, and the number is underlined. I think the underline is good for visibility. However, the buttons for pagination on the existing BMRC site use a dark blue background.
Here is the [News page](https://bmrc.lib.uchicago.edu/news/) with buttons, as an example.
This is to expedite migration to Wagtail and integration into the current BMRC site only.

**Comment by johnjung** [comment]
I made a change to the link color in https://github.com/johnjung/bmrcportal/commit/86f6091b3c1877f5f557bbe37df16e047b0aa1bd. This is now live on the site. There are some button states that the mockups don't cover- I'll review the design as a whole when we do the Wagtail migration.
