### ISSUE TITLE
swap column allocations on home page: member highlight / about the BMRC

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#91]
The member highlight blurb is tending larger than the static content about the BMRC. (Also the link below this should say "the" BMRC.)
I get it that half and half looks dull, but perhaps the member highlight can take 2/3rds while the About the BMRC can take 1/3?
I see that it may have something to do with the side logo image.
If not simple to adjust, I'll have to just cut way down on the verbiage.

**Comment by johnjung** [comment]
In https://github.com/johnjung/bmrcportal/commit/e29743a0677c8434a32ec5130c1fbe3e495149ec, I changed the widths of those columns on the homepage to more closely match [the mockup](https://uchicago.app.box.com/file/805384943051?s=mtv1s2kqnk5x0bhrntkt228nnisxde5p).

I do think the member spotlight text could be edited down, but if you'd like me to change the widths of the columns again, just let me know.

**Comment by MomoMoses** [comment]
Yep, it should be edited down anyway, but this looks better.
