### ISSUE TITLE
Research Help page content and structure

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#93]
Few changes from the old mockup, though the basic page elements look different now. Page has headlines large and medium for text sections, an embedded video with a caption and Creative Commons license, and an embedded PDF, if possible. (First page of PDF shows as image, and it is clickable. Also caption and attribution are required.)

New page element is a callout box on the right hand side of the page [similar to this one](https://bmrc.lib.uchicago.edu/resources/legacy-management-resources-portal/guide-managing-your-archives/) on the BMRC Legacy Management Portal with key word definitions. This is the paragraph at the end of the [content page](https://uchicago.box.com/s/si9ff86oj9iavo4m9h0u3vrmh91otxlp) for research help.

**Comment by johnjung** [comment]
Please provide a link directly to the definitive content for this page so I can be sure I'm looking at the correct content when I evaluate this issue.

**Comment by johnjung** [comment]
See [Research Help Final Draft (1).docx](https://uchicago.app.box.com/s/kmhp6le1shh95kaw4iuitqq90p54i3cg/file/894009760558) and [archives-minizine (1).pdf](https://uchicago.app.box.com/s/kmhp6le1shh95kaw4iuitqq90p54i3cg/file/893972231777)

**Comment by johnjung** [comment]
This is partially implemented in https://github.com/johnjung/bmrcportal/commit/9d45e44faa84083bcbf2d5881dd85291c7b97d6a, and live on the server. I'm going to wait until phase two to evaluate whether I can add the link to the PDF document and sidebar, since we're going to be using existing page types when possible for the Wagtail integration.

**Comment by MomoMoses** [comment]
Ok! There are pages with a sidebar, but will probably need to crater a new
page template in wagtail due to the embedded content.

**Comment by MomoMoses** [comment]
Who will now be responsible for creating new Wagtail page types or adding a content type to a page? Do you know who is assuming that duty as of 2022?

**Comment by johnjung** [comment]
This is a question for Charles or Elisabeth.

**Comment by MomoMoses** [comment]
Most likely Brad B. will be responsible though other members of DLDC might also have that expertise. At least until the new hire is in place.
