### ISSUE TITLE
ExhibitPage nesting

### ISSUE THREAD

**Issue by johnjung** [johnjung/bmrcportal#99]
As per our Zoom conversation on 1/18, ExhibitPage objects should be able to have other ExhibitPage objects as children. The introductory image should be optional. This is now implemented on my dev server and waiting to be pushed to test.

**Comment by johnjung** [comment]
This is now in place on bmrc-test.lib.

**Comment by MomoMoses** [comment]
Looks like the other test page was deleted -- where I was concerned it became a grandchild. Is this the case?
